table 'DIM_Danh mục_Trạng thái Thanh toán'
	excludeFromModelRefresh
	lineageTag: b55e37a6-178c-4c23-81a6-299a9a147d62

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 00a65e07-ceff-45d4-a33a-e35f8c9b20e4
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column StatusPayment
		dataType: string
		lineageTag: a7439ff5-bf72-484b-ade8-05a9e0646876
		summarizeBy: none
		sourceColumn: StatusPayment

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Trạng thái Thanh toán' = m
		mode: import
		queryGroup: 'Danh mục'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUToy4fBihZKMxLwMhZL8wwvzlGJ1opWMgBLOGcc2JKLKxAIA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, StatusPayment = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

