Slg_DH_tiềm_năng = 
VAR zDH = SUMMARIZE( 'FACT_DS Đơn hàng', 'DIM_Danh mục_Phòng ban'[Miền], 'DIM_Danh mục_Phòng ban'[Province], 'DIM_Danh mục_Phòng ban'[District], 'DIM_Danh mục_Phòng ban'[RSM], 'DIM_Danh mục_Phòng ban'[AM], 'DIM_Danh mục_Phòng ban'[Cửa hàng], 'DIM_Danh mục_Nhóm hàng'[Nhóm hàng], 'DIM_Danh mục_Sản phẩm'[Model], 'DIM_Danh mục_Sản phẩm'[Tên hàng], "Slg_DHXL", CALCULATE( SUM('FACT_DS Đơn hàng'[Slg]), 'FACT_DS Đơn hàng'[is_PhieuBanLe_blank] = 1, 'FACT_DS Đơn hàng'[ChasedState] = "Chờ xử lý" ) ) VAR zTon = SUMMARIZE( 'FACT_Warehouse_Current Inventory', 'DIM_Danh mục_Phòng ban'[Miền], 'DIM_Danh mục_Phòng ban'[Province], 'DIM_Danh mục_Phòng ban'[District], 'DIM_Danh mục_Phòng ban'[RSM], 'DIM_Danh mục_Phòng ban'[AM], 'DIM_Danh mục_Phòng ban'[Cửa hàng], 'DIM_Danh mục_Nhóm hàng'[Nhóm hàng], 'DIM_Danh mục_Sản phẩm'[Model], 'DIM_Danh mục_Sản phẩm'[Tên hàng], "Slg_Ton", CALCULATE( SUM('FACT_Warehouse_Current Inventory'[Quantity]), FILTER('DIM_Danh mục_Sản phẩm', 'DIM_Danh mục_Sản phẩm'[ton_ao] <> 1) ) ) VAR zResult = NATURALINNERJOIN(zDH, zTon) RETURN SUMX( zResult, VAR slgDH = [Slg_DHXL] VAR slgTon = [Slg_Ton] RETURN IF( NOT(ISBLANK(slgDH)) && NOT(ISBLANK(slgTon)), MIN(slgDH, slgTon), BLANK() ) )

