table AM_SM_Current_Month
	lineageTag: 039e78fe-fb38-48fe-87eb-c3d0ffb2caf3

	/// các chỉ tiêu VH
	measure '% Đạt tỷ trọng tổng' = ```
			
			SUMX(
			    ALL(NLVH_TieuChi_Q2_2026),
			    CALCULATE([Điểm trọng số])
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: QLVH
		lineageTag: 30aea503-e3d5-4fbc-88b3-d9166f1c5dbc

	measure 'Greater KPI Count' =
			
			VAR t =
			    {
			        [% Hoàn Thành NPS],
			        [% Hoàn thành Online ra SP],
			        [% Hoàn thành Sử dụng AIOv2], [% Hoàn thành TKKD], [% Hoàn thành Tải app]
			    }
			RETURN
			COUNTX(
			    t,
			    IF([Value] > 1, 1)
			)
		formatString: 0
		lineageTag: 1a78bd3b-8ae4-40b4-9bd9-923540107022

	measure 'KPI_Nghỉ việc' =
			
			VAR t =
			    {
			        [% Hoàn thành Chỉ số nghỉ việc]
			    }
			RETURN
			COUNTX(
			    t,
			    IF([Value] > 0, 1)
			)
		formatString: 0
		lineageTag: c2834e72-e127-492e-b551-929920e924b4

	measure 'Tổng KPI Đạt' = ```
			
			COUNTX(
			    FILTER(
			        ALL(NLVH_TieuChi_Q2_2026),
			        CALCULATE([% Hoàn thành]) >= 1
			    ),
			    NLVH_TieuChi_Q2_2026[Key]
			)
			
			```
		formatString: 0
		lineageTag: 8a6c5d4d-45dd-4bc8-9eaa-7232ab9c78f4

	measure 'Đánh giá SHOP' = ```
			
			VAR _score = [% Đạt tỷ trọng tổng]
			VAR _kpi = [Tổng KPI Đạt Shop]
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK(_score) || ISBLANK(_kpi), BLANK(),
			    _score >= 1 && _kpi >= 7, "Xuất sắc tuyệt đối",
			    _score >= 0.8 && _kpi >= 5, "Tốt",
			    _score >= 0.7 && _kpi >= 3, "Khá",
			    _score >= 0.5 && _kpi >= 2, "Kém",
			    "Cảnh báo"
			)
			
			```
		lineageTag: f3515555-f7de-4d5d-89da-7770fe9e9c38

	measure 'Hệ số size Shop' =
			
			VAR size =
			    UPPER(SELECTEDVALUE('DIM_Danh mục_Phòng ban'[Size]))
			RETURN
			SWITCH(
			    TRUE(),
			    size = "S", 1.5,
			    size = "A", 1.2,
			    size = "B", 1,
			    size IN {"C","D"}, 0.8,
			    BLANK()
			)
		lineageTag: f16a4838-84f4-4e96-a220-a9b8ba6fcb18

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// các chỉ tiêu VH
	measure '% Đạt tỷ trọng theo hệ số tổng' = [% Đạt tỷ trọng tổng] * [Hệ số size Shop]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: QLVH
		lineageTag: e6876701-7dfd-4bde-8652-33b7e2318f06

	measure 'QLVH Số cửa hàng AM/SM/SUP' =
			
			DISTINCTCOUNT(AM_SM_Current_Month[SHOP])
		formatString: 0
		lineageTag: 64975935-8fd3-4d17-a703-7b42d3a396ed

	measure 'QLVH Score Shop' = ```
			
			VAR _score =
			    0.20 * [% Hoàn thành Online ra SP]
			    + 0.075 * [% Hoàn thành Trễ DH_2h]
			    + 0.075 * [% Hoàn thành Trễ DH_TT]
			    + 0.10 * [% Hoàn thành Sử dụng AIOv2]
			    + 0.10 * [% Hoàn thành TKKD]
			    + 0.15 * [% Hoàn thành Tải app]
			    + 0.10 * [% Target hiệu quả sử dụng code (3 code)]
			    + 0.10 * [% Hoàn thành Chỉ số nghỉ việc]
			    + 0.10 * [% Hoàn Thành NPS]
			RETURN
			_score
			
			```
		displayFolder: QLVH
		lineageTag: f9831881-8bf3-4355-93d6-59aa93d1f13c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QLVH Tiêu chí đạt Shop' = ```
			
			VAR _online = IF([% Hoàn thành Online ra SP] >= 1, 1, 0)
			VAR _tre2h = IF([% Hoàn thành Trễ DH_2h] >= 1, 1, 0)
			VAR _trett = IF([% Hoàn thành Trễ DH_TT] >= 1, 1, 0)
			VAR _aio = IF([% Hoàn thành Sử dụng AIOv2] >= 1, 1, 0)
			VAR _tkkd = IF([% Hoàn thành TKKD] >= 1, 1, 0)
			VAR _app = IF([% Hoàn thành Tải app] >= 1, 1, 0)
			VAR _budget = IF([% Target hiệu quả sử dụng code (3 code)] >= 1, 1, 0)
			VAR _nghiviec = IF([%  Hoàn thành Chỉ số nghỉ việc_d] >= 1, 1, 0)
			VAR _nps = IF([% Hoàn Thành NPS] >= 1, 1, 0)
			RETURN
			_online + _tre2h + _trett + _aio + _tkkd + _app + _budget + _nghiviec + _nps
			
			```
		formatString: 0
		displayFolder: QLVH
		lineageTag: cea1b877-cb9f-4855-87d8-6c67d17c6eca

	measure 'QLVH Tiêu chí đạt TB AM/SM/SUP' =
			
			AVERAGEX(
			    VALUES(AM_SM_Current_Month[SHOP]),
			    VAR _shop = AM_SM_Current_Month[SHOP]
			    RETURN
			        CALCULATE(
			            [QLVH Tiêu chí đạt Shop],
			            TREATAS({_shop}, 'DIM_Danh mục_Phòng ban'[Cửa hàng])
			        )
			)
		displayFolder: QLVH
		lineageTag: cca1e808-2872-4493-abea-47df334dde71

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QLVH Score TB AM/SM/SUP' = ```
			
			AVERAGEX(
			    VALUES(AM_SM_Current_Month[SHOP]),
			    VAR _shop = AM_SM_Current_Month[SHOP]
			    RETURN
			        CALCULATE(
			            [QLVH Score Shop],
			            TREATAS({_shop}, 'DIM_Danh mục_Phòng ban'[Cửa hàng])
			        )
			)
			
			```
		displayFolder: QLVH
		lineageTag: 8a7713e7-ded6-409c-93f9-5cf9ee38cbb2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QLVH Đánh giá AM/SM/SUP' = ```
			
			VAR _score = [QLVH Score TB AM/SM/SUP]
			VAR _criteria = [QLVH Tiêu chí đạt TB AM/SM/SUP]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(_score), BLANK(),
			        _score >= 1 && _criteria >= 7, "Xuất sắc tuyệt đối",
			        _score >= 0.8 && _criteria >= 5, "Tốt",
			        _score >= 0.7 && _criteria >= 3, "Khá",
			        _score >= 0.5 && _criteria >= 2, "Kém",
			        "Cảnh cáo"
			    )
			
			```
		displayFolder: QLVH
		lineageTag: bdf8cbb2-a8aa-477a-8203-0c4aff778878

	measure 'Số cửa hàng AM/SMKN' = ```
			
			COUNTROWS(
			    FILTER(
			        VALUES('AM_SM_Current_Month'[SHOP]),
			        VAR _shop = 'AM_SM_Current_Month'[SHOP]
			        RETURN
			            CALCULATE(
			                [Dso],
			                TREATAS(
			                    { _shop },
			                    'DIM_Danh mục_Phòng ban'[Cửa hàng]
			                )
			            ) > 0
			    )
			)
			
			```
		formatString: 0
		displayFolder: QLVH
		lineageTag: 25c68b02-3579-4d74-a91b-023f1e832370

	measure '% Đạt tỷ trọng tổng Shop' = ```
			
			    0.20 * [% Hoàn thành Online ra SP]
			    + 0.075 * [% Hoàn thành Trễ DH_2h]
			    + 0.075 * [% Hoàn thành Trễ DH_TT]
			    + 0.10 * [% Hoàn thành Sử dụng AIOv2]
			    + 0.10 * [% Hoàn thành TKKD]
			    + 0.15 * [% Hoàn thành Tải app]
			    + 0.10 * [% Target hiệu quả sử dụng code (3 code)]
			    + 0.10 * [% Hoàn thành Chỉ số nghỉ việc]
			    + 0.10 * [% Hoàn Thành NPS]
			
			```
		displayFolder: QLVH
		lineageTag: 1917fbb8-3fda-456e-8007-a87bbd783204

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tổng KPI Đạt Shop' = ```
			[KPI_Nghỉ việc] + [KPI_Trễ DH] + [% Target hiệu quả sử dụng code (3 code)] + [Greater KPI Count]
			
			```
		formatString: 0
		displayFolder: QLVH
		lineageTag: 8972f08b-437b-4500-bb98-211e181f15f6

	measure 'Tổng hệ số AM/SMKN' = ```
			
			SUMX(
			    FILTER(
			        VALUES('AM_SM_Current_Month'[SHOP]),
			        VAR _shop = 'AM_SM_Current_Month'[SHOP]
			        RETURN
			            CALCULATE(
			                [Dso],
			                TREATAS(
			                    { _shop },
			                    'DIM_Danh mục_Phòng ban'[Cửa hàng]
			                )
			            ) > 0
			    ),
			    VAR _shop = 'AM_SM_Current_Month'[SHOP]
			    RETURN
			        CALCULATE(
			            [Hệ số size Shop],
			            TREATAS(
			                { _shop },
			                'DIM_Danh mục_Phòng ban'[Cửa hàng]
			            )
			        )
			)
			
			```
		displayFolder: QLVH
		lineageTag: bcb2bb31-ce9f-4511-8129-3c6976a1bf71

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Trọng số đạt theo hệ số AM/SMKN' = ```
			
			SUMX(
			    FILTER(
			        VALUES('AM_SM_Current_Month'[SHOP]),
			        VAR _shop = 'AM_SM_Current_Month'[SHOP]
			        RETURN
			            CALCULATE(
			                [Dso],
			                TREATAS(
			                    { _shop },
			                    'DIM_Danh mục_Phòng ban'[Cửa hàng]
			                )
			            ) > 0
			    ),
			    VAR _shop = 'AM_SM_Current_Month'[SHOP]
			    VAR _score =
			        CALCULATE(
			            [% Đạt tỷ trọng tổng Shop],
			            TREATAS(
			                { _shop },
			                'DIM_Danh mục_Phòng ban'[Cửa hàng]
			            )
			        )
			    VAR _heSo =
			        CALCULATE(
			            [Hệ số size Shop],
			            TREATAS(
			                { _shop },
			                'DIM_Danh mục_Phòng ban'[Cửa hàng]
			            )
			        )
			    RETURN
			        _score * _heSo
			)
			
			```
		displayFolder: QLVH
		lineageTag: 6bb6fbb3-5c02-42ee-aed8-2a7e7bb634df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Final Score AM/SMKN' = ```
			
			
			    DIVIDE(
			        [% Trọng số đạt theo hệ số AM/SMKN],
			        [Tổng hệ số AM/SMKN]
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: QLVH
		lineageTag: e97a1d4a-d80a-48b1-b4c6-12e1de40a6cd

	measure 'TB Tiêu chí đạt AM/SMKN' = ```
			
			round(DIVIDE(
			    SUMX(
			        FILTER(
			            VALUES('AM_SM_Current_Month'[SHOP]),
			            VAR _shop = 'AM_SM_Current_Month'[SHOP]
			            RETURN
			                CALCULATE(
			                    [Dso],
			                    TREATAS(
			                        { _shop },
			                        'DIM_Danh mục_Phòng ban'[Cửa hàng]
			                    )
			                ) > 0
			        ),
			        VAR _shop = 'AM_SM_Current_Month'[SHOP]
			        VAR _tieuChiDat =
			            CALCULATE(
			                [Tổng KPI Đạt Shop],
			                TREATAS(
			                    { _shop },
			                    'DIM_Danh mục_Phòng ban'[Cửa hàng]
			                )
			            )
			        VAR _heSo =
			            CALCULATE(
			                [Hệ số size Shop],
			                TREATAS(
			                    { _shop },
			                    'DIM_Danh mục_Phòng ban'[Cửa hàng]
			                )
			            )
			        RETURN
			            _tieuChiDat * _heSo
			    ),
			    [Số cửa hàng AM/SMKN]
			),0)
			
			```
		displayFolder: QLVH
		lineageTag: 2293719b-8b3f-46f8-ae80-75ada8129e32

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Đánh giá AM/SMKN' = ```
			
			VAR _score = [% Final Score AM/SMKN]
			VAR _tieuChi = [TB Tiêu chí đạt AM/SMKN]
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK(_score) || ISBLANK(_tieuChi), BLANK(),
			
			    _score >= 1 && _tieuChi >= 7, "Xuất sắc tuyệt đối",
			    _score >= 0.8 && _tieuChi >= 5, "Tốt",
			    _score >= 0.7 && _tieuChi >= 3, "Khá",
			    _score >= 0.5 && _tieuChi >= 2, "Kém",
			
			    "Cảnh báo"
			)
			
			```
		displayFolder: QLVH
		lineageTag: 9049a533-a4fb-4d74-9522-cae47f78ab8a

	measure 'Số shop theo từng đánh giá' =
			
			VAR _label = SELECTEDVALUE('DIM_Ghi chú_Đánh giá'[Xếp loại])
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('DIM_Danh mục_Phòng ban'[Cửa hàng]),
			    FILTER(
			        ALL('DIM_Danh mục_Phòng ban'),
			        [Đánh giá SHOP] = _label
			    )
			)
		formatString: 0
		lineageTag: e84f2aed-ece8-4002-a801-2818b1a04b98

	measure so_shop_theo_danh_gia =
			
			SUMX(
			    VALUES('DIM_Danh mục_Phòng ban'[Cửa hàng]),
			    VAR _rating = [Đánh giá SHOP]
			    RETURN
			        IF(
			            _rating IN VALUES(Dim_DanhGia[Label]),
			            1,
			            0
			        )
			)
		lineageTag: 9a6d2d87-4143-4532-9746-47aaea907253

	column 'AM Fixed' = ```
			
			VAR _Shop = 'AM_SM_Current_Month'[SHOP]
			VAR _StartDate = 'AM_SM_Current_Month'[StartDate]
			RETURN
			CALCULATE(
			    SELECTEDVALUE('DIM_Danh mục_Shop_AM'[AM]),
			    REMOVEFILTERS('AM_SM_Current_Month'),
			    REMOVEFILTERS('FACT_Đánh giá Shop'),
			    REMOVEFILTERS('Kết quả đánh giá Shop'),
			    FILTER(
			        ALL('DIM_Danh mục_Shop_AM'),
			        'DIM_Danh mục_Shop_AM'[SHOP] = _Shop
			            && 'DIM_Danh mục_Shop_AM'[StartDate] = _StartDate
			    )
			)
			
			```
		lineageTag: e5fdb1f4-90d4-4dbc-b022-987d0abda543
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MNV_SM = ```
			
			VAR _sm =
			    CALCULATE(
			        FIRSTNONBLANK('FACT_Đánh giá SM'[Ma_TenSM], 1),
			        FILTER(
			            'FACT_Đánh giá SM',
			            'FACT_Đánh giá SM'[SHOP] = EARLIER(AM_SM_Current_Month[SHOP])
			                && 'FACT_Đánh giá SM'[StartDate] = EARLIER(AM_SM_Current_Month[StartDate])
			                && 'FACT_Đánh giá SM'[SM/SUP] = EARLIER(AM_SM_Current_Month[SM/SUP])
			        )
			    )
			RETURN
			    IF(
			        ISBLANK(_sm),
			        AM_SM_Current_Month[SM/SUP],
			        _sm
			    )
			
			```
		lineageTag: b14898c5-c3bc-4b48-aff9-35c7bd5e5301
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"AM_SM_Current_Month","TableItemName":"MNV_SM (groups)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'MNV_SM (groups)' =
			SWITCH(
				TRUE,
				ISBLANK('AM_SM_Current_Month'[MNV_SM]),
				"(Blank)",
				'AM_SM_Current_Month'[MNV_SM] IN {"ĐOÀN MỸ DUYÊN",
					"LÊ TUẤN DŨNG",
					"HÀ QUANG DŨNG",
					"HOÀNG VIỆT KIỀU",
					"MAI NGỌC TRƯỜNG",
					"HUỲNH ĐẮC LY",
					"LẠI VŨ LÂM",
					"LÊ VĂN VŨ LINH",
					"NGUYỄN DUY HẢI",
					"NGUYỄN HỒNG SƠN",
					"NGUYỄN NHỰT PHONG",
					"PHẠM TẤN PHONG",
					"PHẠM THỊ HÀM MI",
					"VÕ THỊ YẾN XUÂN",
					"TRẦN QUANG TRƯỜNG"},
				"SM KN",
				'AM_SM_Current_Month'[MNV_SM] IN {"S00007 - BÙI TẤN BỬU TUẤN",
					"S00011 - TRẦN MINH TUYỀN",
					"S00024 - HỒ NGỌC TÚ",
					"S00029 - NGUYỄN VĂN TÀI",
					"S00036 - NGÔ THANH GIÁM",
					"S00038 - NGÔ TẤN ĐIỀN",
					"S00045 - CÙ ĐẠI HOÀNG PHÚ",
					"S00047 - VŨ THỊ QUỲNH",
					"S00052 - TRẦN HOÀNG NAM",
					"S00056 - NGUYỄN CÔNG ĐỊNH",
					"S00057 - PHẠM TUẤN ANH",
					"S00129 - HUỲNH ĐẮC LY",
					"S00058 - NGUYỄN QUỐC TÍN",
					"S00060 - NGUYỄN VĂN SƠN",
					"S00065 - HUỲNH MỸ LINH",
					"S00068 - HUỲNH NGUYỄN THANH TUYỀN",
					"S00069 - NGUYỄN PHƯỚC DƯƠNG",
					"S00092 - LÊ QUANG HÙNG",
					"S00309 - PHAN TRUNG TÍN",
					"S00096 - NGUYỄN HƯƠNG THỊNH",
					"S00106 - LÊ PHÚ THÀNH",
					"S00114 - TRƯƠNG HẢI ĐĂNG",
					"S00121 - NGUYỄN ĐĂNG KHOA",
					"S00128 - NGUYỄN TRẦN LIÊN DUY",
					"S00131 - LÊ ĐỨC THỊNH",
					"S00134 -  LÊ QUỐC HUY",
					"S00151 - NGUYỄN PHỤNG HOÀNG",
					"S00154 - LÊ ĐÌNH ĐỨC",
					"S00164 - VÕ THỊ YẾN XUÂN",
					"S00180 - LÊ HỒNG LONG",
					"S00188 - NGUYỄN CÔNG THỰC",
					"S00194 - CHUNG THỊ CẨM DUYÊN",
					"S00216 - LƯU CÔNG KHANH",
					"S00253 - ỪNG PHÚ HƯNG",
					"S00255 - NGUYỄN PHI LONG",
					"S00329 - NGUYỄN THỊ TRÚC LY",
					"S00267 - NGUYỄN VĂN HOÀNG",
					"S00269 - NGUYỄN HUY HÙNG",
					"S00270 - NGUYỄN VĂN TIẾN",
					"S00273 - TRẦN XUÂN NAM",
					"S00276 - HOÀNG VÕ CUNG GIÁNG MI",
					"S00279 - TRẦN TRỌNG KỲ ANH",
					"S00289 - TRẦN DIỄM HỒNG",
					"S01022 - HOÀNG VIỆT KIỀU",
					"S00314 - TĂNG THIÊN THANH",
					"S00315 - VŨ NGỌC HOÀNG NHUNG",
					"S00324 - NGUYỄN ĐỨC THẮNG",
					"S00327 - PHAN THANH TÙNG",
					"S00333 - NGUYỄN TỨ LONG",
					"S01081 - NGUYỄN TRỌNG NGHĨA",
					"S00338 - NGÔ THỊ BÍCH TRÂM",
					"S00357 - NGUYỄN PHÚC LỢI",
					"S00371 - PHẠM ANH DŨNG",
					"S00372 - HOÀNG VĂN PHONG",
					"S00381 - NGUYỄN NGỌC HÀO",
					"S00384 - VÕ THANH NHÀN",
					"S00394 - TẠ VĂN ĐỘ",
					"S00413 - NGUYỄN THỊ MỸ HẢO",
					"S00415 - LÊ THANH TUẤN",
					"S00427 - NGUYỄN THẾ VINH",
					"S00442 - NGUYỄN THỊ THIÊN VÂN",
					"S00449 - HỒ BẢO TRÂN",
					"S00450 - PHẠM THỊ BÍCH TRÂM",
					"S01249 - NGUYỄN HỒNG SƠN",
					"S00457 - HOÀNG THỊ BÍCH HẠNH",
					"S01015 - TRỊNH XUÂN MẠNH",
					"S01024 - HOÀNG THỊ HOÀI",
					"S01027 - NGUYỄN QUANG TUẤN",
					"S01276 - NGUYỄN DUY HẢI",
					"S01042 - LƯU TIẾN ĐỨC",
					"S01043 - NGUYỄN VIỆT HƯNG",
					"S01079 - NGUYỄN TRỊNH HUY ANH",
					"S01089 - ĐẶNG KHÁNH LINH",
					"S01091 - LÊ CÔNG TUẤN ANH",
					"S01100 - ĐẶNG LÂM ANH",
					"S01240 - HOÀNG TIẾN ĐẠT",
					"S01117 - ĐOÀN VĂN THỊNH",
					"S01162 - NGUYỄN VĂN HƯỞNG",
					"S01176 - NGÔ PHƯƠNG LINH",
					"S01177 - HOÀNG THỊ LAN HƯƠNG",
					"S01216 - PHẠM ĐỨC QUANG",
					"S01218 - TRỊNH XUÂN THƠ",
					"S01222 - TRẦN NGỌC LONG",
					"S01233 - NGUYỄN TIẾN TRỊNH",
					"S01247 - VŨ HỒNG PHÚC",
					"S01272 - LÊ THỊ HƯỜNG",
					"S01274 - NGUYỄN VĂN QUANG",
					"S01285 - ĐINH TIẾN THÀNH",
					"S01309 - PHẠM KIỀU ANH",
					"S01321 - MAI THỊ MỸ HẠNH",
					"S01428 - CAO LẠI HIẾU LƯƠNG",
					"S01473 - PHẠM MINH THUẬN",
					"S01502 - PHẠM CHÍ PHONG",
					"S01537 - TRƯƠNG THỊ MỸ PHƯỢNG",
					"S01541 - ĐÀM THIÊN PHÁT",
					"S01645 - HÀ QUANG DŨNG",
					"S01550 - TÔ NGỌC CHÂN",
					"S01561 - TỐNG MINH QUÂN",
					"S01567 - NGUYỄN PHƯƠNG HỒNG THƯ",
					"S01568 - NGUYỄN VÕ NGUYÊN BÌNH",
					"S01600 - ĐỖ HÙNG ANH",
					"S01620 - NGUYỄN HẢI PHONG",
					"S01642 - TRẦN THANH HOÀN",
					"S01647 - NGUYỄN ĐĂNG MẠNH",
					"S01648 - NGUYỄN QUỐC TRƯỜNG",
					"S01693 - ĐẶNG THỊ THU HƯỜNG",
					"S01694 - NGUYỄN QUANG LINH",
					"S01695 - ĐOÀN HUY HẢI",
					"S01709 - VŨ KHẮC DUNG",
					"S01711 - NGUYỄN KHẮC SƠN",
					"S01717 - NGUYỄN NGỌC TRUNG SƠN",
					"S01724 - NGUYỄN TRÍ DŨNG",
					"S01751 - LIÊU ANH TIẾN",
					"S01820 - NGUYỄN HOÀNG ĐỨC",
					"S02164 - NGUYỄN ĐÌNH TRUNG",
					"S01829 - ĐOÀN TRUNG HIẾU",
					"S01922 - ĐỖ TRƯỜNG DUY",
					"S01925 - CHU LINH HIỆP",
					"S01930 - TRẦN VĂN DUY",
					"S01976 - NGUYỄN THỊ NHÃ PHƯƠNG",
					"S01996 - LÊ HỒNG QUẾ ANH",
					"S01997 - TRƯƠNG QUANG ÂN",
					"S02051 - ĐỖ XUÂN LONG",
					"S02075 - NGUYỄN TÂM TUẤN",
					"S02097 - TRẦN THỤY YẾN NHI",
					"S02100 - VÕ KHÁNH LINH",
					"S02102 - TRƯƠNG QUỐC HUY",
					"S02134 - TRẦN ĐỨC PHÁT",
					"S02144 - NGUYỄN NGỌC TUYẾT TRINH",
					"S02158 - VÕ TRÍ THỨC",
					"S02173 - NGUYỄN BẢO TRUNG",
					"S02195 - NGUYỄN THANH GIA HUY",
					"S02212 - BÙI TRƯỜNG GIANG",
					"S02214 - NGUYỄN MAI THƯƠNG",
					"S02229 - SẦM THỊ LIỄU",
					"S02315 - PHẠM ĐĂNG THÀNH",
					"S02335 - NGUYỄN HUY HOÀNG",
					"S02354 - BÙI HẢI ĐƯỜNG",
					"S02414 - DƯƠNG MINH SANG",
					"S02416 - NGÔ THANH PHƯỚC",
					"S02417 - NGUYỄN HẢI LONG",
					"S02426 - LÊ TRẠC ĐỒNG",
					"S02437 - QUÁCH NGỌC TIẾN",
					"S02453 - ĐOÀN LÊ ĐỨC THỊNH",
					"S02509 - NGUYỄN HOÀNG LINH",
					"S02527 - NGUYỄN VIẾT ĐỨC",
					"S02567 - PHẠM MỸ ÁI",
					"S02708 - PHẠM VIỆT DŨNG",
					"S02598 - PHẠM HOÀNG SƠN",
					"S02605 - NGUYỄN THỊ TRÂM",
					"S02627 - NGUYỄN NGỌC HỒNG",
					"S02654 - PHẠM KIỀU MY",
					"S02681 - LÒ ANH LINH",
					"S02703 - DƯƠNG HỮU LỘC",
					"S02710 - LÊ VĂN QUANG",
					"S02716 - HOÀNG MẠNH ĐOÀN",
					"S02721 - NGUYỄN THỊ CẨM GIANG",
					"S02741 - NGUYỄN THANH DUY",
					"S02743 - NGUYỄN HỒNG QUANG",
					"S02751 - NGUYỄN MINH ĐỨC",
					"S02774 - NGUYỄN THỊ TUYẾT NHUNG",
					"S02810 - TRẦN THÁI NHÂN",
					"S02817 - HUỲNH TẤN TÀI",
					"S03098 - VĂN THỊ LOAN ANH",
					"S02828 - NGUYỄN NGUYÊN HÒA",
					"S02876 - TRẦN QUANG KHÁNH",
					"S03115 - BÙI TRƯỜNG THỌ",
					"S02883 - LƯƠNG HOÀNG THUẬN",
					"S02884 - VÕ NGUYỄN THÙY DƯƠNG",
					"S02913 - ĐẶNG MINH HIẾU",
					"S02916 - PHẠM THÀNH HOÀ",
					"S02931 - TRỊNH MINH LÂM",
					"S02949 - ĐỖ THỊ HƯƠNG GIANG",
					"S02956 - VŨ THỊ HẰNG",
					"S03005 - DIỆP MAI ĐIỀN",
					"S03014 - NGUYỄN THỊ XUÂN NGỌC",
					"S03016 - NGUYÊN MẠNH CƯỜNG",
					"S03021 - NGÔ HOÀNG LAM THUYÊN",
					"S03029 - TRẦN VĂN SƠN",
					"S03151 - NGUYỄN VĂN TÂN",
					"S03152 - NGUYỄN HỒNG NAM",
					"S03182 - NGÔ QUỐC TUẤN",
					"S03192 - NGUYỄN TRẦN HOÀNG THƯƠNG",
					"S03239 - NGUYỄN ANH TÚ",
					"S03284 - PHẠM THẾ QUANG",
					"S03527 - LÊ THỊ THANH THU HỒNG",
					"S03290 - PHẠM ĐÌNH THÁI ANH",
					"S03298 - LÊ HỮU QUANG",
					"S03395 - ĐỖ QUANG DUY",
					"S03413 - VŨ MẠNH KHIÊN",
					"S03420 - ĐẶNG THỊ ANH THƯ",
					"S03422 - NGUYỄN PHƯỚC THÀNH",
					"S03430 - HOÀNG MAI HUÊ",
					"S03431 - CHU TUẤN ANH",
					"S03454 - LIÊU THỊ NGỌC CHÂU",
					"S03463 - TRƯƠNG NGỌC HÒA",
					"S03467 - TRƯƠNG THỊ MỸ HẠNH",
					"S03743 - VÕ PHƯỚC TÀI",
					"S03494 - VÕ THÀNH PHONG",
					"S03517 - PHAN THỊ THÀNH CHUNG",
					"S03546 - ĐỖ VĂN DƯƠNG",
					"S03562 - TRẦN THẾ NAM",
					"S03592 - TRƯƠNG PHƯƠNG ĐÔNG",
					"S03655 - TRẦN MINH TRÍ",
					"S03668 - NGUYỄN THÀNH ĐẠT",
					"S03682 - BÙI HOÀNG KHANG",
					"S03692 - NGUYỄN QUỐC NAM",
					"S03693 - NGUYỄN DUY THANH",
					"S03702 - HUỲNH VẠN NGỌC",
					"S03844 - NGUYỄN NGỌC TRÂN",
					"S03874 - ĐOÀN QUỐC KHẠI",
					"S03907 - NGUYỄN BÉ NGỌC",
					"S03959 - NGUYỄN HÀ VY",
					"S03974 - NGUYỄN TRỌNG QUÂN",
					"S03979 - VŨ ĐỨC PHÚC",
					"S03998 - PHẠM PHÚ ĐẠT",
					"S04024 - PHAN THY VỸ",
					"S04058 - NGUYỄN VĂN ĐỨC",
					"S04069 - TÔ HOÀNG NHÂN",
					"S04114 - NGUYỄN VĂN KIÊN",
					"S04143 - NGUYỄN MINH HIẾU",
					"S04160 - NGUYỄN ĐÌNH BẮC",
					"S04210 - LÊ HOÀNG TUẤN",
					"S04248 - LÊ NGUYỄN THANH VY",
					"S04293 - PHẠM THỊ BÌNH",
					"S04305 - VÕ THỊ NGỌC NƯƠNG",
					"S04307 - LÊ VĂN CHẬN",
					"S04310 - LÂM TẤN LỘC",
					"S04360 - HÀ QUỐC BẢO",
					"S04362 - LÊ HUỲNH THIỆN",
					"S04377 - LƯỜNG ĐỨC NGHĨA",
					"S04383 - TỐNG MINH KIỆT",
					"S04438 - NGUYỄN QUỐC AN PHONG",
					"S04557 - NGUYỄN ĐĂNG KHOA",
					"S04564 - NGUYỄN THANH TRỌNG",
					"S04604 - TÔ MINH ĐỨC",
					"S04616 - NGUYỄN VĂN DŨNG",
					"S05419 - NGUYỄN DƯƠNG HOÀNG KHA",
					"S04643 - PHAN MINH NGHỊ",
					"S04650 - NGUYỄN CÔNG HẬU",
					"S04688 - TRẦN HỮU THỨC",
					"S04707 - TRỊNH CÔNG MINH",
					"S04716 - LÊ HỒNG TỚI",
					"S05261 - ĐOÀN QUANG HUY",
					"S05285 - NGUYỄN VĂN HIỆP",
					"S05418 - THÁI NGỌC TRÌNH",
					"S07444 - VÕ ANH THÔNG",
					"S05526 - TRỊNH DIỄM TRINH",
					"S05759 - ĐẶNG THỊ HUYỀN",
					"S05807 - NGUYỄN HỮU THÁI",
					"S05915 - NGÔ ĐÌNH KHẢI",
					"S05916 - VŨ THÀNH CÔNG",
					"S05927 - NGÔ QUỐC KHÁNH",
					"S06144 - VÕ THANH HẬU",
					"S06168 - PHẠM TIẾN ĐẠT",
					"S06249 - LÂM DUY BÌNH",
					"S06291 - DƯƠNG THÀNH AN",
					"S06321 - PHAN THỊ KIM NHƯ",
					"S06328 - DƯƠNG TUẤN ANH",
					"S06394 - TRẦN PHI HÙNG",
					"S06424 - NGUYỄN HƯNG KHÁNH DUY",
					"S06611 - NGUYỄN THỊ  MỸ LINH",
					"S06739 - TRẦN THÙY LINH",
					"S06841 - TRẦN DUY LỢI",
					"S06893 - TRẦN ANH SƠN",
					"S06925 - VÕ THANH HẢI",
					"S07021 - NGUYỄN DUY TÙNG",
					"S07069 - NGUYỄN ĐỨC VƯƠNG",
					"S07144 - TRẦN HỒ MINH QUANG",
					"S07164 - KIỀU NGỌC TÙNG",
					"S07512 - NGUYỄN LÂM",
					"S08539 - NGUYỄN HOÀNG ANH",
					"S07530 - LÊ TRẦN THÀNH TRAI",
					"S07548 - NGUYỄN THỊ THẮM",
					"S07587 - NGUYỄN THÁI VŨ",
					"S07804 - PHẠM THỊ HẠNH",
					"S07873 - NGÔ TUẤN HIẾU",
					"S07876 - NGUYỄN HOÀNG HUYNH",
					"S07995 - NGUYỄN THỊ THÙY TRANG",
					"S08054 - LƯU QUỐC KHOA",
					"S08116 - NGUYỄN MINH TƯỞNG",
					"S08248 - VÕ NGỌC TÂM",
					"S08261 - NGUYỄN TRUNG THÀNH",
					"S08316 - HỒ NGỌC MUÔN",
					"S08375 - NGUYỄN MINH NHỰT",
					"S08412 - NGUYỄN HOÀNG PHÚC",
					"S08445 - NGUYỄN NGỌC THÀNH",
					"S09193 - VY MINH HIẾU",
					"S09219 - MAI THỊ HỒNG VÂN",
					"S09220 - LÊ CÔNG CƯỜNG",
					"S09388 - NGUYỄN QUÝ ĐẠT",
					"S09435 - HOÀNG MINH HÙNG",
					"S09549 - LÊ VĂN TRUNG",
					"S09984 - HOÀNG ĐÔNG QUANG",
					"S10246 - NINH VĂN THÀNH",
					"S10662 - NGUYỄN NGỌC HIỆP"},
				"SM/SUP",
				'AM_SM_Current_Month'[MNV_SM]
			)
		lineageTag: 78b76202-0cc8-4078-8838-c6aedaa16809
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "AM_SM_Current_Month"
				          }
				        },
				        "Property": "MNV_SM"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"a","Entity":"AM_SM_Current_Month"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"a"}},"Property":"MNV_SM"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"SM KN","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"a"}},"Property":"MNV_SM"}}],"Values":[[{"Literal":{"Value":"'ĐOÀN MỸ DUYÊN'"}}],[{"Literal":{"Value":"'LÊ TUẤN DŨNG'"}}],[{"Literal":{"Value":"'HÀ QUANG DŨNG'"}}],[{"Literal":{"Value":"'HOÀNG VIỆT KIỀU'"}}],[{"Literal":{"Value":"'MAI NGỌC TRƯỜNG'"}}],[{"Literal":{"Value":"'HUỲNH ĐẮC LY'"}}],[{"Literal":{"Value":"'LẠI VŨ LÂM'"}}],[{"Literal":{"Value":"'LÊ VĂN VŨ LINH'"}}],[{"Literal":{"Value":"'NGUYỄN DUY HẢI'"}}],[{"Literal":{"Value":"'NGUYỄN HỒNG SƠN'"}}],[{"Literal":{"Value":"'NGUYỄN NHỰT PHONG'"}}],[{"Literal":{"Value":"'PHẠM TẤN PHONG'"}}],[{"Literal":{"Value":"'PHẠM THỊ HÀM MI'"}}],[{"Literal":{"Value":"'VÕ THỊ YẾN XUÂN'"}}],[{"Literal":{"Value":"'TRẦN QUANG TRƯỜNG'"}}]]}}},{"DisplayName":"SM/SUP","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"a"}},"Property":"MNV_SM"}}],"Values":[[{"Literal":{"Value":"'S00007 - BÙI TẤN BỬU TUẤN'"}}],[{"Literal":{"Value":"'S00011 - TRẦN MINH TUYỀN'"}}],[{"Literal":{"Value":"'S00024 - HỒ NGỌC TÚ'"}}],[{"Literal":{"Value":"'S00029 - NGUYỄN VĂN TÀI'"}}],[{"Literal":{"Value":"'S00036 - NGÔ THANH GIÁM'"}}],[{"Literal":{"Value":"'S00038 - NGÔ TẤN ĐIỀN'"}}],[{"Literal":{"Value":"'S00045 - CÙ ĐẠI HOÀNG PHÚ'"}}],[{"Literal":{"Value":"'S00047 - VŨ THỊ QUỲNH'"}}],[{"Literal":{"Value":"'S00052 - TRẦN HOÀNG NAM'"}}],[{"Literal":{"Value":"'S00056 - NGUYỄN CÔNG ĐỊNH'"}}],[{"Literal":{"Value":"'S00057 - PHẠM TUẤN ANH'"}}],[{"Literal":{"Value":"'S00129 - HUỲNH ĐẮC LY'"}}],[{"Literal":{"Value":"'S00058 - NGUYỄN QUỐC TÍN'"}}],[{"Literal":{"Value":"'S00060 - NGUYỄN VĂN SƠN'"}}],[{"Literal":{"Value":"'S00065 - HUỲNH MỸ LINH'"}}],[{"Literal":{"Value":"'S00068 - HUỲNH NGUYỄN THANH TUYỀN'"}}],[{"Literal":{"Value":"'S00069 - NGUYỄN PHƯỚC DƯƠNG'"}}],[{"Literal":{"Value":"'S00092 - LÊ QUANG HÙNG'"}}],[{"Literal":{"Value":"'S00309 - PHAN TRUNG TÍN'"}}],[{"Literal":{"Value":"'S00096 - NGUYỄN HƯƠNG THỊNH'"}}],[{"Literal":{"Value":"'S00106 - LÊ PHÚ THÀNH'"}}],[{"Literal":{"Value":"'S00114 - TRƯƠNG HẢI ĐĂNG'"}}],[{"Literal":{"Value":"'S00121 - NGUYỄN ĐĂNG KHOA'"}}],[{"Literal":{"Value":"'S00128 - NGUYỄN TRẦN LIÊN DUY'"}}],[{"Literal":{"Value":"'S00131 - LÊ ĐỨC THỊNH'"}}],[{"Literal":{"Value":"'S00134 -  LÊ QUỐC HUY'"}}],[{"Literal":{"Value":"'S00151 - NGUYỄN PHỤNG HOÀNG'"}}],[{"Literal":{"Value":"'S00154 - LÊ ĐÌNH ĐỨC'"}}],[{"Literal":{"Value":"'S00164 - VÕ THỊ YẾN XUÂN'"}}],[{"Literal":{"Value":"'S00180 - LÊ HỒNG LONG'"}}],[{"Literal":{"Value":"'S00188 - NGUYỄN CÔNG THỰC'"}}],[{"Literal":{"Value":"'S00194 - CHUNG THỊ CẨM DUYÊN'"}}],[{"Literal":{"Value":"'S00216 - LƯU CÔNG KHANH'"}}],[{"Literal":{"Value":"'S00253 - ỪNG PHÚ HƯNG'"}}],[{"Literal":{"Value":"'S00255 - NGUYỄN PHI LONG'"}}],[{"Literal":{"Value":"'S00329 - NGUYỄN THỊ TRÚC LY'"}}],[{"Literal":{"Value":"'S00267 - NGUYỄN VĂN HOÀNG'"}}],[{"Literal":{"Value":"'S00269 - NGUYỄN HUY HÙNG'"}}],[{"Literal":{"Value":"'S00270 - NGUYỄN VĂN TIẾN'"}}],[{"Literal":{"Value":"'S00273 - TRẦN XUÂN NAM'"}}],[{"Literal":{"Value":"'S00276 - HOÀNG VÕ CUNG GIÁNG MI'"}}],[{"Literal":{"Value":"'S00279 - TRẦN TRỌNG KỲ ANH'"}}],[{"Literal":{"Value":"'S00289 - TRẦN DIỄM HỒNG'"}}],[{"Literal":{"Value":"'S01022 - HOÀNG VIỆT KIỀU'"}}],[{"Literal":{"Value":"'S00314 - TĂNG THIÊN THANH'"}}],[{"Literal":{"Value":"'S00315 - VŨ NGỌC HOÀNG NHUNG'"}}],[{"Literal":{"Value":"'S00324 - NGUYỄN ĐỨC THẮNG'"}}],[{"Literal":{"Value":"'S00327 - PHAN THANH TÙNG'"}}],[{"Literal":{"Value":"'S00333 - NGUYỄN TỨ LONG'"}}],[{"Literal":{"Value":"'S01081 - NGUYỄN TRỌNG NGHĨA'"}}],[{"Literal":{"Value":"'S00338 - NGÔ THỊ BÍCH TRÂM'"}}],[{"Literal":{"Value":"'S00357 - NGUYỄN PHÚC LỢI'"}}],[{"Literal":{"Value":"'S00371 - PHẠM ANH DŨNG'"}}],[{"Literal":{"Value":"'S00372 - HOÀNG VĂN PHONG'"}}],[{"Literal":{"Value":"'S00381 - NGUYỄN NGỌC HÀO'"}}],[{"Literal":{"Value":"'S00384 - VÕ THANH NHÀN'"}}],[{"Literal":{"Value":"'S00394 - TẠ VĂN ĐỘ'"}}],[{"Literal":{"Value":"'S00413 - NGUYỄN THỊ MỸ HẢO'"}}],[{"Literal":{"Value":"'S00415 - LÊ THANH TUẤN'"}}],[{"Literal":{"Value":"'S00427 - NGUYỄN THẾ VINH'"}}],[{"Literal":{"Value":"'S00442 - NGUYỄN THỊ THIÊN VÂN'"}}],[{"Literal":{"Value":"'S00449 - HỒ BẢO TRÂN'"}}],[{"Literal":{"Value":"'S00450 - PHẠM THỊ BÍCH TRÂM'"}}],[{"Literal":{"Value":"'S01249 - NGUYỄN HỒNG SƠN'"}}],[{"Literal":{"Value":"'S00457 - HOÀNG THỊ BÍCH HẠNH'"}}],[{"Literal":{"Value":"'S01015 - TRỊNH XUÂN MẠNH'"}}],[{"Literal":{"Value":"'S01024 - HOÀNG THỊ HOÀI'"}}],[{"Literal":{"Value":"'S01027 - NGUYỄN QUANG TUẤN'"}}],[{"Literal":{"Value":"'S01276 - NGUYỄN DUY HẢI'"}}],[{"Literal":{"Value":"'S01042 - LƯU TIẾN ĐỨC'"}}],[{"Literal":{"Value":"'S01043 - NGUYỄN VIỆT HƯNG'"}}],[{"Literal":{"Value":"'S01079 - NGUYỄN TRỊNH HUY ANH'"}}],[{"Literal":{"Value":"'S01089 - ĐẶNG KHÁNH LINH'"}}],[{"Literal":{"Value":"'S01091 - LÊ CÔNG TUẤN ANH'"}}],[{"Literal":{"Value":"'S01100 - ĐẶNG LÂM ANH'"}}],[{"Literal":{"Value":"'S01240 - HOÀNG TIẾN ĐẠT'"}}],[{"Literal":{"Value":"'S01117 - ĐOÀN VĂN THỊNH'"}}],[{"Literal":{"Value":"'S01162 - NGUYỄN VĂN HƯỞNG'"}}],[{"Literal":{"Value":"'S01176 - NGÔ PHƯƠNG LINH'"}}],[{"Literal":{"Value":"'S01177 - HOÀNG THỊ LAN HƯƠNG'"}}],[{"Literal":{"Value":"'S01216 - PHẠM ĐỨC QUANG'"}}],[{"Literal":{"Value":"'S01218 - TRỊNH XUÂN THƠ'"}}],[{"Literal":{"Value":"'S01222 - TRẦN NGỌC LONG'"}}],[{"Literal":{"Value":"'S01233 - NGUYỄN TIẾN TRỊNH'"}}],[{"Literal":{"Value":"'S01247 - VŨ HỒNG PHÚC'"}}],[{"Literal":{"Value":"'S01272 - LÊ THỊ HƯỜNG'"}}],[{"Literal":{"Value":"'S01274 - NGUYỄN VĂN QUANG'"}}],[{"Literal":{"Value":"'S01285 - ĐINH TIẾN THÀNH'"}}],[{"Literal":{"Value":"'S01309 - PHẠM KIỀU ANH'"}}],[{"Literal":{"Value":"'S01321 - MAI THỊ MỸ HẠNH'"}}],[{"Literal":{"Value":"'S01428 - CAO LẠI HIẾU LƯƠNG'"}}],[{"Literal":{"Value":"'S01473 - PHẠM MINH THUẬN'"}}],[{"Literal":{"Value":"'S01502 - PHẠM CHÍ PHONG'"}}],[{"Literal":{"Value":"'S01537 - TRƯƠNG THỊ MỸ PHƯỢNG'"}}],[{"Literal":{"Value":"'S01541 - ĐÀM THIÊN PHÁT'"}}],[{"Literal":{"Value":"'S01645 - HÀ QUANG DŨNG'"}}],[{"Literal":{"Value":"'S01550 - TÔ NGỌC CHÂN'"}}],[{"Literal":{"Value":"'S01561 - TỐNG MINH QUÂN'"}}],[{"Literal":{"Value":"'S01567 - NGUYỄN PHƯƠNG HỒNG THƯ'"}}],[{"Literal":{"Value":"'S01568 - NGUYỄN VÕ NGUYÊN BÌNH'"}}],[{"Literal":{"Value":"'S01600 - ĐỖ HÙNG ANH'"}}],[{"Literal":{"Value":"'S01620 - NGUYỄN HẢI PHONG'"}}],[{"Literal":{"Value":"'S01642 - TRẦN THANH HOÀN'"}}],[{"Literal":{"Value":"'S01647 - NGUYỄN ĐĂNG MẠNH'"}}],[{"Literal":{"Value":"'S01648 - NGUYỄN QUỐC TRƯỜNG'"}}],[{"Literal":{"Value":"'S01693 - ĐẶNG THỊ THU HƯỜNG'"}}],[{"Literal":{"Value":"'S01694 - NGUYỄN QUANG LINH'"}}],[{"Literal":{"Value":"'S01695 - ĐOÀN HUY HẢI'"}}],[{"Literal":{"Value":"'S01709 - VŨ KHẮC DUNG'"}}],[{"Literal":{"Value":"'S01711 - NGUYỄN KHẮC SƠN'"}}],[{"Literal":{"Value":"'S01717 - NGUYỄN NGỌC TRUNG SƠN'"}}],[{"Literal":{"Value":"'S01724 - NGUYỄN TRÍ DŨNG'"}}],[{"Literal":{"Value":"'S01751 - LIÊU ANH TIẾN'"}}],[{"Literal":{"Value":"'S01820 - NGUYỄN HOÀNG ĐỨC'"}}],[{"Literal":{"Value":"'S02164 - NGUYỄN ĐÌNH TRUNG'"}}],[{"Literal":{"Value":"'S01829 - ĐOÀN TRUNG HIẾU'"}}],[{"Literal":{"Value":"'S01922 - ĐỖ TRƯỜNG DUY'"}}],[{"Literal":{"Value":"'S01925 - CHU LINH HIỆP'"}}],[{"Literal":{"Value":"'S01930 - TRẦN VĂN DUY'"}}],[{"Literal":{"Value":"'S01976 - NGUYỄN THỊ NHÃ PHƯƠNG'"}}],[{"Literal":{"Value":"'S01996 - LÊ HỒNG QUẾ ANH'"}}],[{"Literal":{"Value":"'S01997 - TRƯƠNG QUANG ÂN'"}}],[{"Literal":{"Value":"'S02051 - ĐỖ XUÂN LONG'"}}],[{"Literal":{"Value":"'S02075 - NGUYỄN TÂM TUẤN'"}}],[{"Literal":{"Value":"'S02097 - TRẦN THỤY YẾN NHI'"}}],[{"Literal":{"Value":"'S02100 - VÕ KHÁNH LINH'"}}],[{"Literal":{"Value":"'S02102 - TRƯƠNG QUỐC HUY'"}}],[{"Literal":{"Value":"'S02134 - TRẦN ĐỨC PHÁT'"}}],[{"Literal":{"Value":"'S02144 - NGUYỄN NGỌC TUYẾT TRINH'"}}],[{"Literal":{"Value":"'S02158 - VÕ TRÍ THỨC'"}}],[{"Literal":{"Value":"'S02173 - NGUYỄN BẢO TRUNG'"}}],[{"Literal":{"Value":"'S02195 - NGUYỄN THANH GIA HUY'"}}],[{"Literal":{"Value":"'S02212 - BÙI TRƯỜNG GIANG'"}}],[{"Literal":{"Value":"'S02214 - NGUYỄN MAI THƯƠNG'"}}],[{"Literal":{"Value":"'S02229 - SẦM THỊ LIỄU'"}}],[{"Literal":{"Value":"'S02315 - PHẠM ĐĂNG THÀNH'"}}],[{"Literal":{"Value":"'S02335 - NGUYỄN HUY HOÀNG'"}}],[{"Literal":{"Value":"'S02354 - BÙI HẢI ĐƯỜNG'"}}],[{"Literal":{"Value":"'S02414 - DƯƠNG MINH SANG'"}}],[{"Literal":{"Value":"'S02416 - NGÔ THANH PHƯỚC'"}}],[{"Literal":{"Value":"'S02417 - NGUYỄN HẢI LONG'"}}],[{"Literal":{"Value":"'S02426 - LÊ TRẠC ĐỒNG'"}}],[{"Literal":{"Value":"'S02437 - QUÁCH NGỌC TIẾN'"}}],[{"Literal":{"Value":"'S02453 - ĐOÀN LÊ ĐỨC THỊNH'"}}],[{"Literal":{"Value":"'S02509 - NGUYỄN HOÀNG LINH'"}}],[{"Literal":{"Value":"'S02527 - NGUYỄN VIẾT ĐỨC'"}}],[{"Literal":{"Value":"'S02567 - PHẠM MỸ ÁI'"}}],[{"Literal":{"Value":"'S02708 - PHẠM VIỆT DŨNG'"}}],[{"Literal":{"Value":"'S02598 - PHẠM HOÀNG SƠN'"}}],[{"Literal":{"Value":"'S02605 - NGUYỄN THỊ TRÂM'"}}],[{"Literal":{"Value":"'S02627 - NGUYỄN NGỌC HỒNG'"}}],[{"Literal":{"Value":"'S02654 - PHẠM KIỀU MY'"}}],[{"Literal":{"Value":"'S02681 - LÒ ANH LINH'"}}],[{"Literal":{"Value":"'S02703 - DƯƠNG HỮU LỘC'"}}],[{"Literal":{"Value":"'S02710 - LÊ VĂN QUANG'"}}],[{"Literal":{"Value":"'S02716 - HOÀNG MẠNH ĐOÀN'"}}],[{"Literal":{"Value":"'S02721 - NGUYỄN THỊ CẨM GIANG'"}}],[{"Literal":{"Value":"'S02741 - NGUYỄN THANH DUY'"}}],[{"Literal":{"Value":"'S02743 - NGUYỄN HỒNG QUANG'"}}],[{"Literal":{"Value":"'S02751 - NGUYỄN MINH ĐỨC'"}}],[{"Literal":{"Value":"'S02774 - NGUYỄN THỊ TUYẾT NHUNG'"}}],[{"Literal":{"Value":"'S02810 - TRẦN THÁI NHÂN'"}}],[{"Literal":{"Value":"'S02817 - HUỲNH TẤN TÀI'"}}],[{"Literal":{"Value":"'S03098 - VĂN THỊ LOAN ANH'"}}],[{"Literal":{"Value":"'S02828 - NGUYỄN NGUYÊN HÒA'"}}],[{"Literal":{"Value":"'S02876 - TRẦN QUANG KHÁNH'"}}],[{"Literal":{"Value":"'S03115 - BÙI TRƯỜNG THỌ'"}}],[{"Literal":{"Value":"'S02883 - LƯƠNG HOÀNG THUẬN'"}}],[{"Literal":{"Value":"'S02884 - VÕ NGUYỄN THÙY DƯƠNG'"}}],[{"Literal":{"Value":"'S02913 - ĐẶNG MINH HIẾU'"}}],[{"Literal":{"Value":"'S02916 - PHẠM THÀNH HOÀ'"}}],[{"Literal":{"Value":"'S02931 - TRỊNH MINH LÂM'"}}],[{"Literal":{"Value":"'S02949 - ĐỖ THỊ HƯƠNG GIANG'"}}],[{"Literal":{"Value":"'S02956 - VŨ THỊ HẰNG'"}}],[{"Literal":{"Value":"'S03005 - DIỆP MAI ĐIỀN'"}}],[{"Literal":{"Value":"'S03014 - NGUYỄN THỊ XUÂN NGỌC'"}}],[{"Literal":{"Value":"'S03016 - NGUYÊN MẠNH CƯỜNG'"}}],[{"Literal":{"Value":"'S03021 - NGÔ HOÀNG LAM THUYÊN'"}}],[{"Literal":{"Value":"'S03029 - TRẦN VĂN SƠN'"}}],[{"Literal":{"Value":"'S03151 - NGUYỄN VĂN TÂN'"}}],[{"Literal":{"Value":"'S03152 - NGUYỄN HỒNG NAM'"}}],[{"Literal":{"Value":"'S03182 - NGÔ QUỐC TUẤN'"}}],[{"Literal":{"Value":"'S03192 - NGUYỄN TRẦN HOÀNG THƯƠNG'"}}],[{"Literal":{"Value":"'S03239 - NGUYỄN ANH TÚ'"}}],[{"Literal":{"Value":"'S03284 - PHẠM THẾ QUANG'"}}],[{"Literal":{"Value":"'S03527 - LÊ THỊ THANH THU HỒNG'"}}],[{"Literal":{"Value":"'S03290 - PHẠM ĐÌNH THÁI ANH'"}}],[{"Literal":{"Value":"'S03298 - LÊ HỮU QUANG'"}}],[{"Literal":{"Value":"'S03395 - ĐỖ QUANG DUY'"}}],[{"Literal":{"Value":"'S03413 - VŨ MẠNH KHIÊN'"}}],[{"Literal":{"Value":"'S03420 - ĐẶNG THỊ ANH THƯ'"}}],[{"Literal":{"Value":"'S03422 - NGUYỄN PHƯỚC THÀNH'"}}],[{"Literal":{"Value":"'S03430 - HOÀNG MAI HUÊ'"}}],[{"Literal":{"Value":"'S03431 - CHU TUẤN ANH'"}}],[{"Literal":{"Value":"'S03454 - LIÊU THỊ NGỌC CHÂU'"}}],[{"Literal":{"Value":"'S03463 - TRƯƠNG NGỌC HÒA'"}}],[{"Literal":{"Value":"'S03467 - TRƯƠNG THỊ MỸ HẠNH'"}}],[{"Literal":{"Value":"'S03743 - VÕ PHƯỚC TÀI'"}}],[{"Literal":{"Value":"'S03494 - VÕ THÀNH PHONG'"}}],[{"Literal":{"Value":"'S03517 - PHAN THỊ THÀNH CHUNG'"}}],[{"Literal":{"Value":"'S03546 - ĐỖ VĂN DƯƠNG'"}}],[{"Literal":{"Value":"'S03562 - TRẦN THẾ NAM'"}}],[{"Literal":{"Value":"'S03592 - TRƯƠNG PHƯƠNG ĐÔNG'"}}],[{"Literal":{"Value":"'S03655 - TRẦN MINH TRÍ'"}}],[{"Literal":{"Value":"'S03668 - NGUYỄN THÀNH ĐẠT'"}}],[{"Literal":{"Value":"'S03682 - BÙI HOÀNG KHANG'"}}],[{"Literal":{"Value":"'S03692 - NGUYỄN QUỐC NAM'"}}],[{"Literal":{"Value":"'S03693 - NGUYỄN DUY THANH'"}}],[{"Literal":{"Value":"'S03702 - HUỲNH VẠN NGỌC'"}}],[{"Literal":{"Value":"'S03844 - NGUYỄN NGỌC TRÂN'"}}],[{"Literal":{"Value":"'S03874 - ĐOÀN QUỐC KHẠI'"}}],[{"Literal":{"Value":"'S03907 - NGUYỄN BÉ NGỌC'"}}],[{"Literal":{"Value":"'S03959 - NGUYỄN HÀ VY'"}}],[{"Literal":{"Value":"'S03974 - NGUYỄN TRỌNG QUÂN'"}}],[{"Literal":{"Value":"'S03979 - VŨ ĐỨC PHÚC'"}}],[{"Literal":{"Value":"'S03998 - PHẠM PHÚ ĐẠT'"}}],[{"Literal":{"Value":"'S04024 - PHAN THY VỸ'"}}],[{"Literal":{"Value":"'S04058 - NGUYỄN VĂN ĐỨC'"}}],[{"Literal":{"Value":"'S04069 - TÔ HOÀNG NHÂN'"}}],[{"Literal":{"Value":"'S04114 - NGUYỄN VĂN KIÊN'"}}],[{"Literal":{"Value":"'S04143 - NGUYỄN MINH HIẾU'"}}],[{"Literal":{"Value":"'S04160 - NGUYỄN ĐÌNH BẮC'"}}],[{"Literal":{"Value":"'S04210 - LÊ HOÀNG TUẤN'"}}],[{"Literal":{"Value":"'S04248 - LÊ NGUYỄN THANH VY'"}}],[{"Literal":{"Value":"'S04293 - PHẠM THỊ BÌNH'"}}],[{"Literal":{"Value":"'S04305 - VÕ THỊ NGỌC NƯƠNG'"}}],[{"Literal":{"Value":"'S04307 - LÊ VĂN CHẬN'"}}],[{"Literal":{"Value":"'S04310 - LÂM TẤN LỘC'"}}],[{"Literal":{"Value":"'S04360 - HÀ QUỐC BẢO'"}}],[{"Literal":{"Value":"'S04362 - LÊ HUỲNH THIỆN'"}}],[{"Literal":{"Value":"'S04377 - LƯỜNG ĐỨC NGHĨA'"}}],[{"Literal":{"Value":"'S04383 - TỐNG MINH KIỆT'"}}],[{"Literal":{"Value":"'S04438 - NGUYỄN QUỐC AN PHONG'"}}],[{"Literal":{"Value":"'S04557 - NGUYỄN ĐĂNG KHOA'"}}],[{"Literal":{"Value":"'S04564 - NGUYỄN THANH TRỌNG'"}}],[{"Literal":{"Value":"'S04604 - TÔ MINH ĐỨC'"}}],[{"Literal":{"Value":"'S04616 - NGUYỄN VĂN DŨNG'"}}],[{"Literal":{"Value":"'S05419 - NGUYỄN DƯƠNG HOÀNG KHA'"}}],[{"Literal":{"Value":"'S04643 - PHAN MINH NGHỊ'"}}],[{"Literal":{"Value":"'S04650 - NGUYỄN CÔNG HẬU'"}}],[{"Literal":{"Value":"'S04688 - TRẦN HỮU THỨC'"}}],[{"Literal":{"Value":"'S04707 - TRỊNH CÔNG MINH'"}}],[{"Literal":{"Value":"'S04716 - LÊ HỒNG TỚI'"}}],[{"Literal":{"Value":"'S05261 - ĐOÀN QUANG HUY'"}}],[{"Literal":{"Value":"'S05285 - NGUYỄN VĂN HIỆP'"}}],[{"Literal":{"Value":"'S05418 - THÁI NGỌC TRÌNH'"}}],[{"Literal":{"Value":"'S07444 - VÕ ANH THÔNG'"}}],[{"Literal":{"Value":"'S05526 - TRỊNH DIỄM TRINH'"}}],[{"Literal":{"Value":"'S05759 - ĐẶNG THỊ HUYỀN'"}}],[{"Literal":{"Value":"'S05807 - NGUYỄN HỮU THÁI'"}}],[{"Literal":{"Value":"'S05915 - NGÔ ĐÌNH KHẢI'"}}],[{"Literal":{"Value":"'S05916 - VŨ THÀNH CÔNG'"}}],[{"Literal":{"Value":"'S05927 - NGÔ QUỐC KHÁNH'"}}],[{"Literal":{"Value":"'S06144 - VÕ THANH HẬU'"}}],[{"Literal":{"Value":"'S06168 - PHẠM TIẾN ĐẠT'"}}],[{"Literal":{"Value":"'S06249 - LÂM DUY BÌNH'"}}],[{"Literal":{"Value":"'S06291 - DƯƠNG THÀNH AN'"}}],[{"Literal":{"Value":"'S06321 - PHAN THỊ KIM NHƯ'"}}],[{"Literal":{"Value":"'S06328 - DƯƠNG TUẤN ANH'"}}],[{"Literal":{"Value":"'S06394 - TRẦN PHI HÙNG'"}}],[{"Literal":{"Value":"'S06424 - NGUYỄN HƯNG KHÁNH DUY'"}}],[{"Literal":{"Value":"'S06611 - NGUYỄN THỊ  MỸ LINH'"}}],[{"Literal":{"Value":"'S06739 - TRẦN THÙY LINH'"}}],[{"Literal":{"Value":"'S06841 - TRẦN DUY LỢI'"}}],[{"Literal":{"Value":"'S06893 - TRẦN ANH SƠN'"}}],[{"Literal":{"Value":"'S06925 - VÕ THANH HẢI'"}}],[{"Literal":{"Value":"'S07021 - NGUYỄN DUY TÙNG'"}}],[{"Literal":{"Value":"'S07069 - NGUYỄN ĐỨC VƯƠNG'"}}],[{"Literal":{"Value":"'S07144 - TRẦN HỒ MINH QUANG'"}}],[{"Literal":{"Value":"'S07164 - KIỀU NGỌC TÙNG'"}}],[{"Literal":{"Value":"'S07512 - NGUYỄN LÂM'"}}],[{"Literal":{"Value":"'S08539 - NGUYỄN HOÀNG ANH'"}}],[{"Literal":{"Value":"'S07530 - LÊ TRẦN THÀNH TRAI'"}}],[{"Literal":{"Value":"'S07548 - NGUYỄN THỊ THẮM'"}}],[{"Literal":{"Value":"'S07587 - NGUYỄN THÁI VŨ'"}}],[{"Literal":{"Value":"'S07804 - PHẠM THỊ HẠNH'"}}],[{"Literal":{"Value":"'S07873 - NGÔ TUẤN HIẾU'"}}],[{"Literal":{"Value":"'S07876 - NGUYỄN HOÀNG HUYNH'"}}],[{"Literal":{"Value":"'S07995 - NGUYỄN THỊ THÙY TRANG'"}}],[{"Literal":{"Value":"'S08054 - LƯU QUỐC KHOA'"}}],[{"Literal":{"Value":"'S08116 - NGUYỄN MINH TƯỞNG'"}}],[{"Literal":{"Value":"'S08248 - VÕ NGỌC TÂM'"}}],[{"Literal":{"Value":"'S08261 - NGUYỄN TRUNG THÀNH'"}}],[{"Literal":{"Value":"'S08316 - HỒ NGỌC MUÔN'"}}],[{"Literal":{"Value":"'S08375 - NGUYỄN MINH NHỰT'"}}],[{"Literal":{"Value":"'S08412 - NGUYỄN HOÀNG PHÚC'"}}],[{"Literal":{"Value":"'S08445 - NGUYỄN NGỌC THÀNH'"}}],[{"Literal":{"Value":"'S09193 - VY MINH HIẾU'"}}],[{"Literal":{"Value":"'S09219 - MAI THỊ HỒNG VÂN'"}}],[{"Literal":{"Value":"'S09220 - LÊ CÔNG CƯỜNG'"}}],[{"Literal":{"Value":"'S09388 - NGUYỄN QUÝ ĐẠT'"}}],[{"Literal":{"Value":"'S09435 - HOÀNG MINH HÙNG'"}}],[{"Literal":{"Value":"'S09549 - LÊ VĂN TRUNG'"}}],[{"Literal":{"Value":"'S09984 - HOÀNG ĐÔNG QUANG'"}}],[{"Literal":{"Value":"'S10246 - NINH VĂN THÀNH'"}}],[{"Literal":{"Value":"'S10662 - NGUYỄN NGỌC HIỆP'"}}]]}}}]}

		annotation SummarizationSetBy = Automatic

	column SM/SUP
		lineageTag: 6693bfcd-322f-4eac-8d76-e11b8db77639
		summarizeBy: none
		isNameInferred
		sourceColumn: FACT_Đánh giá SM[SM/SUP]

		annotation SummarizationSetBy = Automatic

	column SHOP
		lineageTag: 4459fa94-1973-4e84-8299-5cadbbb2fe35
		summarizeBy: none
		isNameInferred
		sourceColumn: FACT_Đánh giá SM[SHOP]

		annotation SummarizationSetBy = Automatic

	column StartDate
		formatString: General Date
		lineageTag: aa30581c-0aac-4fac-89e6-c49d2949ee1e
		summarizeBy: none
		isNameInferred
		sourceColumn: FACT_Đánh giá SM[StartDate]

		variation Variation
			isDefault
			relationship: ee73c359-1aec-4c75-a09c-af4b53bad508
			defaultHierarchy: LocalDateTable_8d608702-9c4e-42ae-90a6-4c661ad23256.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition AM_SM_Current_Month = calculated
		mode: import
		source =
				
				var _start = CALCULATE (
				    MAX ( 'DIM_Danh mục_Ngày'[Đầu tháng] ),
				    FILTER (
				        'DIM_Danh mục_Ngày',
				        'DIM_Danh mục_Ngày'[Ngày_IsActive] = 1
				    )
				)
				var SM =
				SUMMARIZE(FILTER('FACT_Đánh giá SM', 'FACT_Đánh giá SM'[MNV] <> BLANK() && NOT 'FACT_Đánh giá SM'[SHOP] IN {"CPS-HNO-DDA-B2B"} && 'FACT_Đánh giá SM'[StartDate] = _start), 'FACT_Đánh giá SM'[SM/SUP], 'FACT_Đánh giá SM'[SHOP], 'FACT_Đánh giá SM'[StartDate])
				var SMKN =
				SUMMARIZE(FILTER('DIM_Danh mục_Shop_SMKN', 'DIM_Danh mục_Shop_SMKN'[SMKN] <> BLANK() && 'DIM_Danh mục_Shop_SMKN'[StartDate] = MAX('DIM_Danh mục_Shop_SMKN'[StartDate])), 'DIM_Danh mục_Shop_SMKN'[SMKN], 'DIM_Danh mục_Shop_SMKN'[SHOP], 'DIM_Danh mục_Shop_SMKN'[StartDate])
				RETURN UNION(SM, SMKN)

	annotation PBI_Id = 09d4af87e57c44cd95801020055b52a8

