table FACT_Code_TargetSuDung
	lineageTag: 31b286fd-847c-49f7-9c7d-aa81f6eccb37

	measure _min_date =
			
			min('DIM_Danh mục_Ngày'[Date])
		formatString: General Date
		lineageTag: d5d12690-a6ab-49fb-beb1-1f4298127ee8

	measure _target_su_dung_% =
			
			var _date =
			    maxx(
			        filter(
			
			            FACT_Code_TargetSuDung,
			
			            FACT_Code_TargetSuDung[Ngày bắt đầu] <= [_min_date]
			        ),
			        FACT_Code_TargetSuDung[Ngày bắt đầu]
			    )
			var _result =
			    if(
			        isinscope(DIM_PromotionCode[PromotionCode]),
			
			        max(FACT_Code_TargetSuDung[Tỷ trọng hạn mức]),
			
			        average(FACT_Code_TargetSuDung[Tỷ trọng hạn mức])
			    )
			return
			    _result
		lineageTag: 70be9194-669b-45cf-99df-6cd067ab303e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _target_su_dung_abs = ```
			
			VAR _date = 
			    MAXX(
			        FILTER(
			            FACT_Code_TargetSuDung,
			            FACT_Code_TargetSuDung[Ngày bắt đầu] <= [_min_date]
			        ),
			        FACT_Code_TargetSuDung[Ngày bắt đầu]
			    )
			VAR _table =
			    ADDCOLUMNS(
			        VALUES(DIM_PromotionCode[PromotionCodeId]),
			        "target_per",
			            CALCULATE(
			                MAX(FACT_Code_TargetSuDung[Tỷ trọng hạn mức]),
			                FACT_Code_TargetSuDung[Ngày bắt đầu] = _date
			            ),
			        "dso",
			            SWITCH( TRUE(),
			                DIM_PromotionCode[PromotionCodeId] IN {3283,3284,3285,3287}, [Dso],
			                DIM_PromotionCode[PromotionCodeId] IN {2859,3121}, [Dso_BHMR],
			                DIM_PromotionCode[PromotionCodeId] IN {3742}, [Dso_IPHONE],
			                0
			            )
			    )   
			
			VAR _result =
			    SUMX(
			        _table,
			        [target_per] * [dso]
			    )
			
			RETURN
			    IF(
			        ISBLANK([Giá trị code_used]), 
			        BLANK(),
			        _result
			    )
			```
		lineageTag: 91311bbe-c1b4-409a-a7c0-865bcc8ce8b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_target_su_dung_abs_Dự kiến' = [_target_su_dung_abs]*[Run Rate]
		lineageTag: 88eb8627-d541-41f0-84cd-ecab86c2d3bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Chênh lệch Giá trị sử dụng' =
			
			[_target_su_dung_abs] - [Giá trị code_used]
		lineageTag: f67e059d-e8dc-49a7-8fb3-cfa3f1dae665

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Chênh lệch Giá trị sử dụng_%' =
			
			divide(
			    [Chênh lệch Giá trị sử dụng],
			    [_target_su_dung_abs],
			    blank()
			)
		lineageTag: bb9da884-0620-484a-a00d-29bc10cef18c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ngày bắt đầu'
		dataType: dateTime
		formatString: Long Date
		lineageTag: be5a41f1-5a62-4b58-b2fe-70a238cdbb9c
		summarizeBy: none
		sourceColumn: Ngày bắt đầu

		variation Variation
			isDefault
			relationship: 9ba3d980-c6d5-444a-891d-28fcc78e2e7f
			defaultHierarchy: LocalDateTable_7d94704b-a7b8-4eef-84d3-c1b2b7403317.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Id chương trình'
		dataType: int64
		formatString: 0
		lineageTag: 3c0adccf-81a6-47f2-be92-2509947c50c1
		summarizeBy: none
		sourceColumn: Id chương trình

		annotation SummarizationSetBy = Automatic

	column 'Chương trình'
		dataType: string
		lineageTag: 3e80d7b4-d4da-40e0-a784-ada3e1ee62ed
		summarizeBy: none
		sourceColumn: Chương trình

		annotation SummarizationSetBy = Automatic

	column 'Tỷ trọng hạn mức'
		dataType: double
		lineageTag: 1fa9743e-6e89-4c14-8c97-5acd4f9d3f7d
		summarizeBy: sum
		sourceColumn: Tỷ trọng hạn mức

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Doanh số'
		dataType: string
		lineageTag: 6160cf7b-9dab-43d9-991d-48889aa51fce
		summarizeBy: none
		sourceColumn: Doanh số

		annotation SummarizationSetBy = Automatic

	column 'Hạn mức cho phép'
		dataType: string
		lineageTag: 9d993515-22d7-466b-8b32-e8de1b12c298
		summarizeBy: none
		sourceColumn: Hạn mức cho phép

		annotation SummarizationSetBy = Automatic

	column 'Chênh lệch hạn mức'
		dataType: string
		lineageTag: 715dbf97-ba6c-4daf-9ebf-3d75c4701312
		summarizeBy: none
		sourceColumn: Chênh lệch hạn mức

		annotation SummarizationSetBy = Automatic

	partition FACT_Code_TargetSuDung = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject="cellphones-data-platform"]){[Name="cellphones-data-platform"]}[Data], "---""dataset_id=54cfc7b0-4cd1-4ab1-87fd-85c6e135d1ac""#(lf)SELECT#(lf)#(lf)  DATE(#(lf)  TIMESTAMP_MILLIS(ngay_bat_dau),#(lf)  ""Asia/Ho_Chi_Minh""#(lf)) as ngay_bat_dau,#(lf)id_chuong_trinh,#(lf)chuong_trinh,#(lf)ty_trong_han_muc,#(lf)doanh_so,#(lf)han_muc_cho_phep,#(lf)chenh_lech_han_muc#(lf)from cellphones-data-platform.cps_larkbase.cps_vh_su_dung_code", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"ngay_bat_dau", "Ngày bắt đầu"}, {"id_chuong_trinh", "Id chương trình"}, {"chuong_trinh", "Chương trình"}, {"ty_trong_han_muc", "Tỷ trọng hạn mức"}, {"doanh_so", "Doanh số"}, {"han_muc_cho_phep", "Hạn mức cho phép"}, {"chenh_lech_han_muc", "Chênh lệch hạn mức"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

