table NLVH_TieuChi_Q2_2026
	lineageTag: fb30d3ff-f195-4c7f-9025-e4b96bae893d

	measure 'NLVH Target' = ```
			
			VAR _key = SELECTEDVALUE(NLVH_TieuChi_Q2_2026[Key])
			VAR _shop = SELECTEDVALUE('DIM_Danh mục_Phòng ban'[Cửa hàng])
			VAR _zone = SELECTEDVALUE('adhoc_shop_zone_mappings'[zone])
			VAR _region = SELECTEDVALUE('DIM_Danh mục_Miền'[Miền])
			VAR _size = SELECTEDVALUE('DIM_Danh mục_Phòng ban'[Size])
			VAR _targetNghiViec =
			    SWITCH(
			        TRUE(),
			        _region = "Miền Nam" && _size = "S", 2.0,
			        _region = "Miền Nam" && _size IN { "A", "B" }, 1.5,
			        _region = "Miền Nam" && _size IN { "C", "D" }, 1.0,
			        _region = "Miền Bắc" && _size IN { "S", "A" }, 2.0,
			        _region = "Miền Bắc" && _size = "B", 1.5,
			        _region = "Miền Bắc" && _size IN { "C", "D" }, 1.0,
			        BLANK()
			    )
			VAR _targetLogistics =
			    SWITCH(
			        TRUE(),
			        _zone = "Zone 1", "2h ≤  15% | TT ≤ 15%",
			        _zone = "Zone 2", "2h ≤  15% | TT ≤ 20%",
			        _zone = "Zone 3", "TT ≤  20%",
			        "2h ≤ 15% | TT ≤  15%"
			    )
			RETURN
			SWITCH(
			    TRUE(),
			    _key = "ONLINE", "≥ 65%",
			    _key = "LOGISTICS", _targetLogistics,
			    _key = "AIOV2", "≥ 70%",
			    _key = "TKKD", "≥ 90%",
			    _key = "TAI_APP", IF(CONTAINSSTRING(_shop, "HCM") || CONTAINSSTRING(_shop, "HNO"), "≥ 50%", "≥ 55%"),
			    _key = "CODE", "Không vượt hạn mức",
			    _key = "NGHI_VIEC", "≤ " & FORMAT(_targetNghiViec, "0.0") & " nhân sự/quý",
			    _key = "NPS", "≥ 94%",
			    BLANK()
			)
			
			```
		lineageTag: 87698d02-e2ff-4d1b-a058-1eb823d18f3f

	measure 'Thực đạt' = ```
			
			VAR _key = SELECTEDVALUE(NLVH_TieuChi_Q2_2026[Key])
			VAR _actual2h = [% Thực đạt Trễ hạn_DH Giao 2 giờ]
			VAR _actualTT = [% Thực đạt Trễ hạn_DH Giao thông thường]
			VAR _codeVuot = [Số code vượt hạn mức (3 code)] VAR zone = SELECTEDVALUE(adhoc_shop_zone_mappings[zone])
			RETURN
			SWITCH(
			    TRUE(),
			    _key = "ONLINE" && NOT ISBLANK([% Thực đạt Online ra SP]), FORMAT([% Thực đạt Online ra SP], "0.00%"),
			    _key = "LOGISTICS",
			        VAR _text2h =
			        IF(
			            ISBLANK(_actual2h) && zone IN {"Zone 1", "Zone 2"},
			            "2h: 0%",
			            "2h: " & FORMAT(_actual2h, "0.00%")
			    )
			        VAR _textTT = IF(ISBLANK(_actualTT), BLANK(), "TT: " & FORMAT(_actualTT, "0.00%"))
			        RETURN
			            SWITCH(
			                TRUE(),
			                NOT ISBLANK(_text2h) && NOT ISBLANK(_textTT), _text2h & " | " & _textTT,
			                NOT ISBLANK(_text2h), _text2h,
			                NOT ISBLANK(_textTT), _textTT,
			                BLANK()
			            ),
			    _key = "AIOV2" && NOT ISBLANK([% Thực đạt Sử dụng AioV2]), FORMAT([% Thực đạt Sử dụng AioV2], "0.00%"),
			    _key = "TKKD" && NOT ISBLANK([NLVH Actual TKKD]), FORMAT([NLVH Actual TKKD], "0.00%"),
			    _key = "TAI_APP" && NOT ISBLANK([% Thực đạt Tải app]), FORMAT([% Thực đạt Tải app], "0.00%"),
			    _key = "CODE" && NOT ISBLANK(_codeVuot), "Vượt " & FORMAT(_codeVuot, "0") & "/3 code",
			    _key = "NGHI_VIEC" && NOT ISBLANK(SELECTEDVALUE('gsheet_chi_so_nghi_viec'[Thực đạt Chỉ số nghỉ việc])),
			        FORMAT(SELECTEDVALUE('gsheet_chi_so_nghi_viec'[Thực đạt Chỉ số nghỉ việc]), "0.00"),
			    _key = "NPS" && NOT ISBLANK([% Thực đạt NPS]), FORMAT([% Thực đạt NPS], "0.00%"),
			    BLANK()
			)
			
			```
		lineageTag: 242b4fe6-8c80-46ee-ad39-349869383403

	measure 'NLVH % Hoàn thành Logistics' = ```
			
			VAR _score2h = [% Hoàn thành Trễ DH_2h]
			VAR _scoreTT = [% Hoàn thành Trễ DH_TT]
			VAR _has2h = NOT ISBLANK(_score2h)
			VAR _hasTT = NOT ISBLANK(_scoreTT)
			RETURN
			SWITCH(
			    TRUE(),
			    _has2h && _hasTT, DIVIDE(_score2h + _scoreTT, 2),
			    _has2h, _score2h,
			    _hasTT, _scoreTT,
			    BLANK()
			)
			
			```
		lineageTag: a947f230-69aa-41f2-92fe-00a3a8a117b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Hoàn thành' = ```
			
			VAR _key = SELECTEDVALUE(NLVH_TieuChi_Q2_2026[Key])
			RETURN
			SWITCH(
			    TRUE(),
			    _key = "ONLINE", [% Hoàn thành Online ra SP],
			    _key = "LOGISTICS", [NLVH % Hoàn thành Logistics],
			    _key = "AIOV2", [% Hoàn thành Sử dụng AIOv2],
			    _key = "TKKD", [% Hoàn thành TKKD],
			    _key = "TAI_APP", [% Hoàn thành Tải app],
			    _key = "CODE", [% Target hiệu quả sử dụng code (3 code)],
			    _key = "NGHI_VIEC", [% Hoàn thành Chỉ số nghỉ việc],
			    _key = "NPS", [% Hoàn Thành NPS],
			    BLANK()
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c00ea468-ad36-49b3-8e13-b5ba55f864d7

	measure 'Điểm trọng số' = ```
			
			VAR _score = [% Hoàn thành]
			VAR _weight = SELECTEDVALUE(NLVH_TieuChi_Q2_2026[Trọng số])
			RETURN
			IF(
			    ISBLANK(_score) || ISBLANK(_weight),
			    BLANK(),
			    _score * _weight
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a889729b-7dda-46a2-876e-64d323e3a790

	measure 'NLVH Source' = ```
			
			SELECTEDVALUE(NLVH_TieuChi_Q2_2026[Source])
			
			```
		lineageTag: 2a42e794-88b7-4de7-ad6b-f8c750a53dc0

	measure 'NLVH Source URL' = ```
			
			SELECTEDVALUE(NLVH_TieuChi_Q2_2026[Source URL])
			
			```
		lineageTag: 8e4b8309-6595-4bd9-844e-f700233d0d1a

	measure 'NLVH Actual TKKD' = ```
			
			VAR _shops =
			    VALUES('DIM_Danh mục_Phòng ban'[Cửa hàng])
			RETURN
			CALCULATE(
			    AVERAGE('adhoc_tkkd'[% Thực đạt TKKD]),
			    TREATAS(_shops, 'adhoc_tkkd'[Cửa hàng])
			)
			
			```
		lineageTag: 1734514b-a82a-4fdd-a5a6-8d8c8ad93240

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sort
		formatString: 0
		lineageTag: 0319918c-96bc-4296-ae22-d9d288f20d89
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Sort]

		annotation SummarizationSetBy = Automatic

	column Key
		lineageTag: 1e479379-cd1a-4f12-9b00-231df6d500ed
		summarizeBy: none
		isNameInferred
		sourceColumn: [Key]

		annotation SummarizationSetBy = Automatic

	column 'Tên tiêu chí'
		lineageTag: 60f180e0-7c18-438d-8741-fa175470103d
		summarizeBy: none
		isNameInferred
		sourceColumn: [Tên tiêu chí]
		sortByColumn: 'Trọng số'

		annotation SummarizationSetBy = Automatic

	column 'Trọng số'
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: cbb96465-a758-4813-93a7-c4a58e5a7b3e
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Trọng số]

		annotation SummarizationSetBy = User

	column Source
		lineageTag: fd3c6acd-4045-4bf6-9698-d79e60a4b446
		summarizeBy: none
		isNameInferred
		sourceColumn: [Source]

		annotation SummarizationSetBy = Automatic

	column 'Source URL'
		lineageTag: e687e4b7-e579-40a4-a411-9042f75a4677
		summarizeBy: none
		isNameInferred
		sourceColumn: [Source URL]

		annotation SummarizationSetBy = Automatic

	partition NLVH_TieuChi_Q2_2026 = calculated
		mode: import
		source = ```
				
				DATATABLE(
				    "Sort", INTEGER,
				    "Key", STRING,
				    "Tên tiêu chí", STRING,
				    "Trọng số", DOUBLE,
				    "Source", STRING,
				    "Source URL", STRING,
				    {
				        { 1, "ONLINE", "Tỷ lệ thành công đơn Online", 0.20, "Tỷ lệ chốt đơn", "https://app.powerbi.com/groups/2eec82ee-b4e5-4426-b93f-7b7086579fec/reports/670eb49c-13be-4f80-8b5c-317c52d78960/5ae17638f961fc269343?ctid=05d55c2c-4b15-4b42-afa7-7eb8d2ba93b3&experience=power-bi" },
				        { 2, "LOGISTICS", "Tỷ lệ trễ đơn giao hàng", 0.15, "Logistics", "https://app.powerbi.com/groups/me/apps/61cc54f0-cc69-4623-8318-a16c1d0d5177/reports/4e97cd09-53c9-4307-9582-bf8e032849ce/ReportSectiond766277740a9ccc842eb?ctid=05d55c2c-4b15-4b42-afa7-7eb8d2ba93b3&experience=power-bi&clientSideAuth=0" },
				        { 3, "AIOV2", "Tỷ lệ sử dụng AIOv2", 0.10, "AIOv2", "https://app.powerbi.com/groups/me/apps/ddbe614f-d1af-4b62-b554-8b2243d4dcb4/reports/bb0ef9c8-45dc-481d-83c9-a9d004a14e56/5ae17638f961fc269343?experience=power-bi" },
				        { 4, "TKKD", "Điểm TKKD", 0.10, "Link", "https://docs.google.com/spreadsheets/d/17aktG0NdZRCAbAPmQtgvRGGC7Y_spMS6__FhHt-X9hU/edit?gid=568528235" },
				        { 5, "TAI_APP", "%Tải app", 0.15, "Link", "https://app.powerbi.com/groups/2eec82ee-b4e5-4426-b93f-7b7086579fec/reports/a49acab3-450d-4d03-b2c1-4fbdf25ac2f7/73a7e255e088246b3e45?experience=power-bi" },
				        { 6, "CODE", "Hiệu quả sử dụng ngân sách", 0.10, "VH_Sử dụng code", "https://app.powerbi.com/groups/2eec82ee-b4e5-4426-b93f-7b7086579fec/reports/5d9bd206-256f-46fa-8d29-be5339034a56/ReportSectionc1f711461dbf4f8b1251?experience=power-bi" },
				        { 7, "NGHI_VIEC", "Chỉ số nghỉ việc", 0.10, "Miền Nam / Miền Bắc", "https://dieuphuc.sg.larksuite.com/sheets/IlrOsuUhahNPUWtdtcMlyrtgg5c?from=auth_notice&hash=c020872c5d2fd9373bc9398280dbea09" },
				        { 8, "NPS", "NPS", 0.10, "8.CS_Kết quả khảo sát CS", "https://app.powerbi.com/groups/me/apps/a6f45915-b12e-4380-b2b0-1ee68630d90f/reports/f6ef267d-9f28-4680-ad14-3a1da87d7b8a/ReportSectionf465b3adb95d00ecd029?experience=power-bi" }
				    }
				)
				
				```

	annotation PBI_Id = 06f01472edcc4ce988b6fee674e4eacc

