table 'FACT_DS Đơn hàng'
	lineageTag: 4a9d3cb6-e3eb-4d6d-9281-60b1105a8d34

	column PhuongThuc
		dataType: string
		lineageTag: 0ff0592b-b959-4457-905c-05d60b716408
		summarizeBy: none
		sourceColumn: PhuongThuc

		annotation SummarizationSetBy = Automatic

	column StoreCode
		dataType: string
		lineageTag: 8b810e91-a5b0-4eb2-b954-3174aa2dbacb
		summarizeBy: none
		sourceColumn: StoreCode

		annotation SummarizationSetBy = Automatic

	column TrangThaiDon
		dataType: string
		lineageTag: c0c4c2f8-1bd7-480b-9f32-97bf12bfd75d
		summarizeBy: none
		sourceColumn: TrangThaiDon

		annotation SummarizationSetBy = Automatic

	column TrangThaiThanhToan
		dataType: string
		lineageTag: 14c83e21-6e79-439c-b545-7ef53fc54e7d
		summarizeBy: none
		sourceColumn: TrangThaiThanhToan

		annotation SummarizationSetBy = Automatic

	column TrangThaiLienHe
		dataType: string
		lineageTag: e6ca6fbd-89b4-4f72-9156-5c61e87bd926
		summarizeBy: none
		sourceColumn: TrangThaiLienHe

		annotation SummarizationSetBy = Automatic

	column SoDonHang
		dataType: string
		lineageTag: 2039d1e9-825c-4cb8-9174-49e40b2cd77a
		summarizeBy: none
		sourceColumn: SoDonHang

		annotation SummarizationSetBy = Automatic

	column NgayDat
		dataType: dateTime
		formatString: Short Date
		lineageTag: 305810f3-2158-4a6c-8069-d867b89d4e68
		summarizeBy: none
		sourceColumn: NgayDat

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NhomHang
		dataType: string
		lineageTag: a136eb65-37cf-4876-aa8c-c047a3ab5f68
		summarizeBy: none
		sourceColumn: NhomHang

		annotation SummarizationSetBy = Automatic

	column MaHang
		dataType: string
		lineageTag: 3b4120e7-14ae-4b77-af86-3298ae66564b
		summarizeBy: none
		sourceColumn: MaHang

		annotation SummarizationSetBy = Automatic

	column TenHang
		dataType: string
		lineageTag: e176b6ed-5f0d-4166-94cf-6d56675e11f9
		summarizeBy: none
		sourceColumn: TenHang

		annotation SummarizationSetBy = Automatic

	column Slg
		dataType: double
		lineageTag: 48aae204-792d-4727-bd51-66b3b9d0c821
		summarizeBy: sum
		sourceColumn: Slg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TongDon
		dataType: double
		formatString: #,0
		lineageTag: 186c2154-0478-446f-81a6-c269a6367534
		summarizeBy: sum
		sourceColumn: TongDon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column TraTruoc
		dataType: double
		lineageTag: 0d67452a-deb1-4f82-8865-984a8bb56efb
		summarizeBy: sum
		sourceColumn: TraTruoc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MNV_NguoiLap
		dataType: string
		lineageTag: 3c753254-baab-44c3-a29b-c8fc54610b09
		summarizeBy: none
		sourceColumn: MNV_NguoiLap

		annotation SummarizationSetBy = Automatic

	column NguoiLap
		dataType: string
		lineageTag: 7d91a210-85d0-4407-96da-0ad8591a8cfb
		summarizeBy: none
		sourceColumn: NguoiLap

		annotation SummarizationSetBy = Automatic

	column ChucDanh
		dataType: string
		lineageTag: a9e1cfdd-89fd-4d71-9845-74e48b8c3a2a
		summarizeBy: none
		sourceColumn: ChucDanh

		annotation SummarizationSetBy = Automatic

	column PhongBan
		dataType: string
		lineageTag: 0ec7fb76-cf67-4578-abba-96eafb1b700c
		summarizeBy: none
		sourceColumn: PhongBan

		annotation SummarizationSetBy = Automatic

	column MNV_NguoiXuLy
		dataType: string
		lineageTag: d45ae30a-b34b-4525-9454-23b64025b7a2
		summarizeBy: none
		sourceColumn: MNV_NguoiXuLy

		annotation SummarizationSetBy = Automatic

	column NguoiXuLy
		dataType: string
		lineageTag: 9467ffc6-8b2b-4029-91ff-93d85fbb1ea8
		summarizeBy: none
		sourceColumn: NguoiXuLy

		annotation SummarizationSetBy = Automatic

	column NgayXuLy
		dataType: dateTime
		formatString: Long Date
		lineageTag: a4b237a1-1661-432a-bfc6-2572e7bf671f
		summarizeBy: none
		sourceColumn: NgayXuLy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LyDoHuyDon
		dataType: string
		lineageTag: fb07d7bc-938e-4179-aa8d-500fd2302999
		summarizeBy: none
		sourceColumn: LyDoHuyDon

		annotation SummarizationSetBy = Automatic

	column DonTaoTu
		dataType: string
		lineageTag: 29714fb2-3eab-4a54-ad4a-2897b3c09865
		summarizeBy: none
		sourceColumn: DonTaoTu

		annotation SummarizationSetBy = Automatic

	column Nguon
		dataType: string
		lineageTag: 478d9e2f-2a09-4474-818f-4102e7f595d7
		summarizeBy: none
		sourceColumn: Nguon

		annotation SummarizationSetBy = Automatic

	column IsPreOrder
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ae89bdc7-6e86-45cf-a082-672cd653f8cd
		summarizeBy: none
		sourceColumn: IsPreOrder

		annotation SummarizationSetBy = Automatic

	column IsOnline
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 019ebe33-1ed1-41a5-a4f2-ecca50c5062e
		summarizeBy: none
		sourceColumn: IsOnline

		annotation SummarizationSetBy = Automatic

	column IsOverDue
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3dbb9501-f7eb-4317-9200-0893dffa0a25
		summarizeBy: none
		sourceColumn: IsOverDue

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: ec3834b9-33a1-4988-a44b-23cc4340cc41
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0ad7a48a-18c5-4736-acea-2ee46a03298e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderSource =
			
			VAR department =
			    SWITCH (
			        TRUE (),
			        'FACT_DS Đơn hàng'[PhongBan]
			            IN {
			                "CSKH - Hotline",
			                "Nhóm Hotline CellphoneS",
			                "Phòng chăm sóc khách hàng"
			            }, "Hotline",
			        'FACT_DS Đơn hàng'[PhongBan]
			            IN {
			                "Nhóm chatline CellphoneS",
			                "Nhóm CTV Chatline CellphoneS",
			                "Nhóm Facebook CellphoneS"
			            }, "Chatline",
			        "Shop"
			    )
			RETURN
			    SWITCH (
			        TRUE (),
			        'FACT_DS Đơn hàng'[IsOnline]
			            && department = "Hotline", "Đơn Hotline xử lý",
			        'FACT_DS Đơn hàng'[IsOnline]
			            && department = "Chatline", "Đơn Chatline xử lý",
			        'FACT_DS Đơn hàng'[IsOnline]
			            && department = "Shop", "Đơn Shop xử lý",
			        'FACT_DS Đơn hàng'[IsOnline] = FALSE ()
			            && department = "Hotline", "Đơn KH gọi Hotline",
			        'FACT_DS Đơn hàng'[IsOnline] = FALSE ()
			            && department = "Chatline", "Đơn KH nhắn tin Chatline",
			        'FACT_DS Đơn hàng'[IsOnline] = FALSE ()
			            && department = "Shop", "Đơn Offline",
			        BLANK ()
			    )
		lineageTag: 0a2765a8-5a49-4fac-88b6-872c387b1639
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column StatusPayment =
			
			IF('FACT_DS Đơn hàng'[TrangThaiThanhToan] = "Đã thanh toán", "Đã thanh toán", "Chưa thanh toán")
		lineageTag: b90ab7e1-c9bd-492b-8aa4-4fef80fefd6a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column OrderState =
			
			SWITCH(TRUE(),
			'FACT_DS Đơn hàng'[TrangThaiDon] = "Đã xuất kho", "Thành công",
			'FACT_DS Đơn hàng'[TrangThaiDon] = "Hủy đơn", "Thất bại",
			"Chờ xử lý")
		lineageTag: 901679e6-2df3-44e7-b860-4b652d72021b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Product_HighestPrice = ```
			
			VAR maxprice = 
			    CALCULATE(
			        MAX('FACT_DS Đơn hàng'[TongDon]),
			        ALLEXCEPT('FACT_DS Đơn hàng', 'FACT_DS Đơn hàng'[SoDonHang])
			    )
			RETURN
			IF('FACT_DS Đơn hàng'[TongDon] = maxprice, 1, 0)
			```
		formatString: 0
		lineageTag: 73362ceb-c398-46fd-814d-dc0ab2177db7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ChasedState =
			
			VAR count_active =
			    CALCULATE (
			        SUM ( 'FACT_DS Đơn hàng'[IsChased] ),
			        FILTER (
			            'FACT_DS Đơn hàng',
			            'FACT_DS Đơn hàng'[OrderState] = "Thất bại"
			                && 'FACT_DS Đơn hàng'[SoDonHang]
			                    = EARLIER ( 'FACT_DS Đơn hàng'[SoDonHang] )
			        )
			    )
			RETURN
			    SWITCH (
			        TRUE (),
			        ISBLANK ( 'FACT_DS Đơn hàng'[IsChased] ), 'FACT_DS Đơn hàng'[OrderState],
			        count_active > 0, "Đã chuyển đổi",
			        "Hủy đơn"
			    )
		lineageTag: cfcd5a88-4c4f-41c2-87d0-042481547184
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column NgayDat_Date = DATEVALUE('FACT_DS Đơn hàng'[NgayDat])
		formatString: General Date
		lineageTag: 2f240da4-4a90-46e8-a2a2-61b557b79886
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Đơn_giá = DIVIDE('FACT_DS Đơn hàng'[TongDon], 'FACT_DS Đơn hàng'[Slg], BLANK())
		formatString: #,0
		lineageTag: 511b2f63-6255-4d55-a081-c4485e9aaab0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Miền = RELATED('DIM_Danh mục_Kho'[Miền])
		lineageTag: 652caf2e-ebcd-4619-a98f-3505204e18f9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Phân_quyền_KD = 'FACT_DS Đơn hàng'[NhomHang] &"-"& 'FACT_DS Đơn hàng'[Miền]
		lineageTag: 5d47af6d-a452-4440-bb1d-941288b96c17
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DiDong
		dataType: string
		lineageTag: da58975c-ef45-4136-b831-d35c1818b150
		summarizeBy: none
		sourceColumn: DiDong

		annotation SummarizationSetBy = Automatic

	column 'Loại ca' = ```
			
			VAR giobatdau = TIME(8, 0, 0)
			VAR gioketthuc = TIME(21, 0, 0)
			VAR gio =  IF('FACT_DS Đơn hàng'[NgayDat]> 'FACT_DS Đơn hàng'[NgayDat], 'FACT_DS Đơn hàng'[NgayDat], 'FACT_DS Đơn hàng'[NgayDat])
			VAR giodat = TIME(HOUR(gio), MINUTE(gio), SECOND(gio))
			
			
			VAR duration =
			    IF(
			        AND(giodat >= giobatdau, giodat <= gioketthuc), 
			        "Trong giờ làm", 
			        "Ngoài giờ làm"
			    )
			
			RETURN
			    duration
			
			```
		lineageTag: 765b42a3-342d-41a0-9b75-13553a069051
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column IsChased
		dataType: int64
		formatString: 0
		lineageTag: f55c20fe-29f9-4902-b005-c3336b658385
		summarizeBy: sum
		sourceColumn: IsChased

		annotation SummarizationSetBy = Automatic

	column is_PhieuBanLe_blank
		dataType: int64
		formatString: 0
		lineageTag: eee7cf46-6972-4870-b6f3-1762b8447b6e
		summarizeBy: sum
		sourceColumn: is_PhieuBanLe_blank

		annotation SummarizationSetBy = Automatic

	partition 'FACT_DS Đơn hàng' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([Implementation="2.0"]){[Name="cellphones-data-platform"]}[Data], "---""dataset_id=8cc95609-f041-4368-a7a2-25617b22271a""#(lf)-- HN--#(lf)WITH#(lf)  tempbill_hn AS (#(lf)    SELECT#(lf)      sbd.SOOrderDetailId,#(lf)      ag.AutoCode,#(lf)      ag.CreateDate AS Date,#(lf)      asb.FireCompleted,#(lf)      asb.BillDate#(lf)    FROM `cellphones-data-platform.sqlserver_htv_hn_dbo.vw_Acc_StoreBillDetail` sbd#(lf)    JOIN `cellphones-data-platform.sqlserver_htv_hn_dbo.vw_Acc_General` ag#(lf)      ON ag.Id = sbd.StoreBillId#(lf)    JOIN `cellphones-data-platform.sqlserver_htv_hn_dbo.vw_Acc_StoreBill` asb#(lf)      ON ag.Id = asb.Id#(lf)    JOIN `cellphones-data-platform.cps_cdc_sep_hn_dbo.SO_OrderDetail` sd#(lf)      ON sbd.SOOrderDetailId = sd.Id#(lf)    JOIN `cellphones-data-platform.cps_cdc_sep_hn_dbo.SO_Order` so#(lf)      ON sd.OrderId = so.Id#(lf)    WHERE#(lf)      DATE(so.CreatedDate)#(lf)        >= DATE_ADD(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL -6 MONTH)#(lf)      AND ag.ReplaceById IS NULL#(lf)    GROUP BY 1, 2, 3, 4, 5#(lf)  ),#(lf)  hn AS (#(lf)    SELECT DISTINCT#(lf)      iem.Name AS PhuongThuc,#(lf)      es.code AS StoreCode,#(lf)      CASE#(lf)        WHEN so.MethodId IN (14, 56, 57, 58, 59)#(lf)          THEN#(lf)            CASE#(lf)              WHEN sot.Id = 4#(lf)                THEN#(lf)                  CASE#(lf)                    WHEN FireCompleted = TRUE AND BillDate IS NOT NULL#(lf)                      THEN 'Đã hoàn thành'#(lf)                    WHEN BillDate IS NOT NULL THEN 'Đã xuất kho'#(lf)                    ELSE 'Đã tiếp nhận/Đã tư vấn'#(lf)                    END#(lf)              WHEN sot.Id = 5 THEN 'Đã tiếp nhận/Chưa tư vấn'#(lf)              WHEN sot.Id = 6 THEN 'Sẵn sàng hàng hóa'#(lf)              WHEN sot.Id = 7 THEN 'Hủy đơn'#(lf)              WHEN sot.Id = 8 THEN 'Đã xuất kho'#(lf)              WHEN sot.Id = 13 THEN 'Lưu thông tin'#(lf)              WHEN sot.Id = 15 THEN 'Chờ thanh toán'#(lf)              ELSE sot.Name#(lf)              END#(lf)        ELSE#(lf)          CASE#(lf)            WHEN FireCompleted = TRUE AND BillDate IS NOT NULL#(lf)              THEN 'Đã hoàn thành'#(lf)            WHEN BillDate IS NOT NULL THEN 'Đã xuất kho'#(lf)            ELSE sot.Name#(lf)            END#(lf)        END AS TrangThaiDon,#(lf)      CASE so.StatusPaymentId#(lf)        WHEN 1 THEN 'Chờ thanh toán'#(lf)        WHEN 2 THEN 'Đã thanh toán'#(lf)        ELSE NULL#(lf)        END AS TrangThaiThanhToan,#(lf)      soc.Name AS TrangThaiLienHe,#(lf)      -- so.OrderCode                                                                                            AS MaDatHang,#(lf)      so.AutoCode AS SoDonHang,#(lf)      tempbill_hn.AutoCode AS PhieuBanLe,#(lf)      DATE(so.CreatedDate) AS NgayDat,#(lf)      so.ContactPhone AS DiDong,#(lf)      -- so.OtherPhone                                                                                           AS DTLienHe,#(lf)      spg.Name AS NhomHang,#(lf)      sp.code AS MaHang,#(lf)      sp.Name AS TenHang,#(lf)      SUM(od.Quantity) AS Slg,#(lf)      SUM(od.ProductAmount - od.DiscountAmount - COALESCE(od.UnpaidAmount, 0))#(lf)        AS TongDon,#(lf)      SUM(so.PayBankAmount) + SUM(so.PayCashAmount) AS TraTruoc,#(lf)      UPPER(sperCreate.Code) AS MNV_NguoiLap,#(lf)      sperCreate.FullName AS NguoiLap,#(lf)      empTitle.Name AS ChucDanh,#(lf)      departmentEmpCreate.Name AS PhongBan,#(lf)      UPPER(sper.Code) AS MNV_NguoiXuLy,#(lf)      sper.FullName AS NguoiXuLy,#(lf)      DATE(so.ReviewByDate) AS NgayXuLy,#(lf)      sr.name AS LyDoHuyDon,#(lf)      CASE so.PlatformId#(lf)        WHEN 1 THEN 'Mobile - AIO'#(lf)        ELSE 'Sep Desktop'#(lf)        END AS DonTaoTu,#(lf)      CASE so.SourceId#(lf)        WHEN 1 THEN 'Web'#(lf)        WHEN 2 THEN 'Facebook'#(lf)        WHEN 3 THEN 'Chat'#(lf)        WHEN 4 THEN 'Gọi điện'#(lf)        WHEN 5 THEN 'Zalo'#(lf)        ELSE NULL#(lf)        END AS Nguon,#(lf)      COALESCE(so.PreOrder, FALSE) AS IsPreOrder,#(lf)      so.OnlineNo IS NOT NULL AND so.OnlineNo != '' AS IsOnline,#(lf)      DATETIME(so.Deadline) AS Deadline,#(lf)      CURRENT_DATETIME() > DATETIME(so.Deadline)#(lf)        OR COALESCE(#(lf)          so.PreOrder AND CURRENT_DATETIME() > DATETIME(so.AppointmentDate),#(lf)          FALSE) AS IsOverDue,#(lf)      'HN' AS Region,#(lf)      tempbill_hn.Date AS NgayBanLe#(lf)    FROM `cellphones-data-platform.cps_cdc_sep_hn_dbo.SO_OrderDetail` od#(lf)    INNER JOIN `cellphones-data-platform.cps_cdc_sep_hn_dbo.SO_Order` so#(lf)      ON od.OrderId = so.Id#(lf)    INNER JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Store_ImportExportMethod`#(lf)        iem#(lf)      ON iem.Id = so.MethodId#(lf)    INNER JOIN `cellphones-data-platform.cps_cdc_sep_hn_dbo.Shared_Product` sp#(lf)      ON sp.Id = od.ProductId#(lf)    LEFT JOIN `cellphones-data-platform.cps_cdc_sep_hn_dbo.SO_OrderState` sot#(lf)      ON sot.Id = so.StateId#(lf)    LEFT JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.ERP_Status` soc#(lf)      ON#(lf)        soc.TransactionCode = 'SOContact'#(lf)        AND SAFE_CAST(soc.Code AS INT64) = so.ContactStateId#(lf)    LEFT JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Shared_ProductGroup` spg#(lf)      ON spg.Id = sp.ProductGroupId#(lf)    LEFT JOIN `cellphones-data-platform.cps_cdc_sep_hn_dbo.ERP_Store` es#(lf)      ON es.Id = od.OutputStoreId#(lf)    LEFT JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Shared_Person` sper#(lf)      ON sper.Id = so.ReviewById#(lf)    LEFT JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Shared_Person` sperCreate#(lf)      ON sperCreate.Id = so.CreatedById#(lf)    LEFT JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.ERP_Employee` eeCreate#(lf)      ON eeCreate.Id = sperCreate.Id#(lf)    LEFT JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.ERP_EmployeeTitle` empTitle#(lf)      ON empTitle.Id = eeCreate.TitleId#(lf)    LEFT JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Shared_Department`#(lf)        departmentEmpCreate#(lf)      ON departmentEmpCreate.Id = eeCreate.DepartmentId#(lf)    LEFT JOIN tempbill_hn#(lf)      ON tempbill_hn.SOOrderDetailId = od.Id#(lf)    LEFT JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Store_Reason` sr#(lf)      ON sr.id = so.IOReasonId#(lf)    WHERE#(lf)      1 = 1#(lf)      AND DATE(so.CreatedDate)#(lf)        >= DATE_ADD(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL -6 MONTH)#(lf)      AND so.MethodId IN (14, 57, 58)#(lf)      AND so.ReplaceById IS NULL#(lf)    GROUP BY#(lf)      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 17, 18, 19, 20, 21, 22, 23, 24,#(lf)      25, 26, 27, 28, 29, 30, 31#(lf)  ),#(lf)#(lf)  -- HCM--#(lf)  tempbill_hcm AS (#(lf)    SELECT#(lf)      sbd.SOOrderDetailId,#(lf)      ag.AutoCode,#(lf)      ag.CreateDate AS Date,#(lf)      asb.FireCompleted,#(lf)      asb.BillDate#(lf)    FROM `cellphones-data-platform.sqlserver_dprt_hcm_dbo.vw_Acc_StoreBillDetail` sbd#(lf)    JOIN `cellphones-data-platform.sqlserver_dprt_hcm_dbo.vw_Acc_General` ag#(lf)      ON ag.Id = sbd.StoreBillId#(lf)    JOIN `cellphones-data-platform.sqlserver_dprt_hcm_dbo.vw_Acc_StoreBill` asb#(lf)      ON ag.Id = asb.Id#(lf)    JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.SO_OrderDetail` sd#(lf)      ON sbd.SOOrderDetailId = sd.Id#(lf)    JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.SO_Order` so#(lf)      ON sd.OrderId = so.Id#(lf)    WHERE#(lf)      DATE(so.CreatedDate)#(lf)        >= DATE_ADD(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL -6 MONTH)#(lf)      AND ag.ReplaceById IS NULL#(lf)    GROUP BY 1, 2, 3, 4, 5#(lf)  ),#(lf)  hcm AS (#(lf)    SELECT DISTINCT#(lf)      iem.Name AS PhuongThuc,#(lf)      es.code AS StoreCode,#(lf)      CASE#(lf)        WHEN so.MethodId IN (14, 56, 57, 58, 59)#(lf)          THEN#(lf)            CASE#(lf)              WHEN sot.Id = 4#(lf)                THEN#(lf)                  CASE#(lf)                    WHEN FireCompleted = TRUE AND BillDate IS NOT NULL#(lf)                      THEN 'Đã hoàn thành'#(lf)                    WHEN BillDate IS NOT NULL THEN 'Đã xuất kho'#(lf)                    ELSE 'Đã tiếp nhận/Đã tư vấn'#(lf)                    END#(lf)              WHEN sot.Id = 5 THEN 'Đã tiếp nhận/Chưa tư vấn'#(lf)              WHEN sot.Id = 6 THEN 'Sẵn sàng hàng hóa'#(lf)              WHEN sot.Id = 7 THEN 'Hủy đơn'#(lf)              WHEN sot.Id = 8 THEN 'Đã xuất kho'#(lf)              WHEN sot.Id = 13 THEN 'Lưu thông tin'#(lf)              WHEN sot.Id = 15 THEN 'Chờ thanh toán'#(lf)              ELSE sot.Name#(lf)              END#(lf)        ELSE#(lf)          CASE#(lf)            WHEN FireCompleted = TRUE AND BillDate IS NOT NULL#(lf)              THEN 'Đã hoàn thành'#(lf)            WHEN BillDate IS NOT NULL THEN 'Đã xuất kho'#(lf)            ELSE sot.Name#(lf)            END#(lf)        END AS TrangThaiDon,#(lf)      CASE so.StatusPaymentId#(lf)        WHEN 1 THEN 'Chờ thanh toán'#(lf)        WHEN 2 THEN 'Đã thanh toán'#(lf)        ELSE NULL#(lf)        END AS TrangThaiThanhToan,#(lf)      soc.Name AS TrangThaiLienHe,#(lf)      -- so.OrderCode                                                                                            AS MaDatHang,#(lf)      so.AutoCode AS SoDonHang,#(lf)      tempbill_hcm.AutoCode AS PhieuBanLe,#(lf)      DATE(so.CreatedDate) AS NgayDat,#(lf)      so.ContactPhone AS DiDong,#(lf)      -- so.OtherPhone                                                                                           AS DTLienHe,#(lf)      spg.Name AS NhomHang,#(lf)      sp.code AS MaHang,#(lf)      sp.Name AS TenHang,#(lf)      SUM(od.Quantity) AS Slg,#(lf)      SUM(od.ProductAmount - od.DiscountAmount - COALESCE(od.UnpaidAmount, 0))#(lf)        AS TongDon,#(lf)      SUM(so.PayBankAmount) + SUM(so.PayCashAmount) AS TraTruoc,#(lf)      UPPER(sperCreate.Code) AS MNV_NguoiLap,#(lf)      sperCreate.FullName AS NguoiLap,#(lf)      empTitle.Name AS ChucDanh,#(lf)      departmentEmpCreate.Name AS PhongBan,#(lf)      UPPER(sper.Code) AS MNV_NguoiXuLy,#(lf)      sper.FullName AS NguoiXuLy,#(lf)      DATE(so.ReviewByDate) AS NgayXuLy,#(lf)      sr.name AS LyDoHuyDon,#(lf)      CASE so.PlatformId#(lf)        WHEN 1 THEN 'Mobile - AIO'#(lf)        ELSE 'Sep Desktop'#(lf)        END AS DonTaoTu,#(lf)      CASE so.SourceId#(lf)        WHEN 1 THEN 'Web'#(lf)        WHEN 2 THEN 'Facebook'#(lf)        WHEN 3 THEN 'Chat'#(lf)        WHEN 4 THEN 'Gọi điện'#(lf)        WHEN 5 THEN 'Zalo'#(lf)        ELSE NULL#(lf)        END AS Nguon,#(lf)      COALESCE(so.PreOrder, FALSE) AS IsPreOrder,#(lf)      so.OnlineNo IS NOT NULL AND so.OnlineNo != '' AS IsOnline,#(lf)      DATETIME(so.Deadline) AS Deadline,#(lf)      CURRENT_DATETIME() > DATETIME(so.Deadline)#(lf)        OR COALESCE(#(lf)          so.PreOrder AND CURRENT_DATETIME() > DATETIME(so.AppointmentDate),#(lf)          FALSE) AS IsOverDue,#(lf)      'HCM' AS Region,#(lf)      tempbill_hcm.Date AS NgayBanLe#(lf)    FROM `cellphones-data-platform.cps_cdc_sep_hcm_dbo.SO_OrderDetail` od#(lf)    INNER JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.SO_Order` so#(lf)      ON od.OrderId = so.Id#(lf)    INNER JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Store_ImportExportMethod`#(lf)        iem#(lf)      ON iem.Id = so.MethodId#(lf)    INNER JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Shared_Product` sp#(lf)      ON sp.Id = od.ProductId#(lf)    LEFT JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.SO_OrderState` sot#(lf)      ON sot.Id = so.StateId#(lf)    LEFT JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.ERP_Status` soc#(lf)      ON#(lf)        soc.TransactionCode = 'SOContact'#(lf)        AND SAFE_CAST(soc.Code AS INT64) = so.ContactStateId#(lf)    LEFT JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Shared_ProductGroup` spg#(lf)      ON spg.Id = sp.ProductGroupId#(lf)    LEFT JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.ERP_Store` es#(lf)      ON es.Id = od.OutputStoreId#(lf)    LEFT JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Shared_Person` sper#(lf)      ON sper.Id = so.ReviewById#(lf)    LEFT JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Shared_Person` sperCreate#(lf)      ON sperCreate.Id = so.CreatedById#(lf)    LEFT JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.ERP_Employee` eeCreate#(lf)      ON eeCreate.Id = sperCreate.Id#(lf)    LEFT JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.ERP_EmployeeTitle` empTitle#(lf)      ON empTitle.Id = eeCreate.TitleId#(lf)    LEFT JOIN#(lf)      `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Shared_Department`#(lf)        departmentEmpCreate#(lf)      ON departmentEmpCreate.Id = eeCreate.DepartmentId#(lf)    LEFT JOIN tempbill_hcm#(lf)      ON tempbill_hcm.SOOrderDetailId = od.Id#(lf)    LEFT JOIN `cellphones-data-platform.cps_cdc_sep_hcm_dbo.Store_Reason` sr#(lf)      ON sr.id = so.IOReasonId#(lf)    WHERE#(lf)      1 = 1#(lf)      AND DATE(so.CreatedDate)#(lf)        >= DATE_ADD(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL -6 MONTH)#(lf)      AND so.MethodId IN (14, 57, 58)#(lf)      AND so.ReplaceById IS NULL#(lf)    GROUP BY#(lf)      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 17, 18, 19, 20, 21, 22, 23, 24,#(lf)      25, 26, 27, 28, 29, 30, 31#(lf)  ),#(lf)  fact_ds_don_hang AS (#(lf)    SELECT *, DATE(NgayDat) Date FROM hn#(lf)    UNION ALL#(lf)    SELECT *, DATE(NgayDat) Date FROM hcm#(lf)  ),#(lf)  fact_sale_doanh_so_ban AS (#(lf)    SELECT#(lf)      DATETIME(CreateDate) AS CreateDate,#(lf)      DMC3,#(lf)      AutoCode,#(lf)      ProductCode,#(lf)      ProductName,#(lf)      MethodName,#(lf)      Region,#(lf)      StoreCode,#(lf)      Price,#(lf)      ContactPhone,#(lf)      Smember,#(lf)      SaleEmployeeCode,#(lf)      SaleEmployeeName,#(lf)      SOOrderAutoCode,#(lf)      SOOrderOnlineNo,#(lf)      IsOnlineOrderLine,#(lf)      IsB2B,#(lf)      SUM(amount) AS Dso,#(lf)      SUM(quantity) AS Slg,#(lf)    FROM#(lf)      `cellphones-data-platform.cps_sales_datamart.cps_cdc_sep_union_dbo_sales_transaction`#(lf)    WHERE#(lf)      IsSales = 1#(lf)      AND DATE(CreateDate) < CURRENT_DATE()#(lf)      AND DATE(CreateDate)#(lf)        >= DATE_SUB(DATE_TRUNC(current_date, MONTH), INTERVAL 5 MONTH)#(lf)      AND NOT ContactPhone IN ('0942482682', '0979453264')#(lf)      AND NOT AutoCode LIKE '%#%'#(lf)      AND NOT StoreCode IN (#(lf)        'HCM.KHO', 'HN.KHO', 'HN.KHOLUUTRU', 'HCM.KHOLUUTRU', 'HN.PKL',#(lf)        'HN.DT2', 'HCM.MXTCC', 'HN.BHPK', 'HN.DT')#(lf)    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17#(lf)    UNION ALL#(lf)    SELECT#(lf)      DATETIME(CreateDate) AS CreateDate,#(lf)      DMC3,#(lf)      AutoCode,#(lf)      ProductCode,#(lf)      ProductName,#(lf)      MethodName,#(lf)      Region,#(lf)      StoreCode,#(lf)      Price,#(lf)      ContactPhone,#(lf)      Smember,#(lf)      SaleEmployeeCode,#(lf)      SaleEmployeeName,#(lf)      SOOrderAutoCode,#(lf)      SOOrderOnlineNo,#(lf)      IsOnlineOrderLine,#(lf)      IsB2B,#(lf)      SUM(amount) AS Dso,#(lf)      SUM(quantity) AS Slg,#(lf)    FROM#(lf)      `cellphones-data-platform.cps_sales_datamart.cps_stream_sep_union_dbo_sales_transaction`#(lf)    WHERE#(lf)      IsSales = 1#(lf)      AND DATE(CreateDate) = CURRENT_DATE()#(lf)      AND NOT ContactPhone IN ('0942482682', '0979453264')#(lf)      AND NOT AutoCode LIKE '%#%'#(lf)      AND NOT StoreCode IN (#(lf)        'HCM.KHO', 'HN.KHO', 'HN.KHOLUUTRU', 'HCM.KHOLUUTRU', 'HN.PKL',#(lf)        'HN.DT2', 'HCM.MXTCC', 'HN.BHPK', 'HN.DT')#(lf)    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17#(lf)  )#(lf)SELECT#(lf)  a.* EXCEPT (PhieuBanLe, NgayBanLe, Deadline),#(lf)  IF(PhieuBanLe IS NULL, 1, 0) AS is_PhieuBanLe_blank,#(lf)  CASE#(lf)    WHEN a.TrangThaiDon = 'Hủy đơn'#(lf)      THEN#(lf)        COALESCE(#(lf)          (#(lf)            SELECT COUNT(*)#(lf)            FROM fact_ds_don_hang b#(lf)            WHERE#(lf)              b.TrangThaiDon = 'Hủy đơn'#(lf)              AND b.NhomHang = a.NhomHang#(lf)              AND b.DiDong = a.DiDong#(lf)              AND b.NgayDat > a.NgayDat#(lf)              AND b.NgayDat <= DATE_ADD(a.NgayDat, INTERVAL 3 DAY)#(lf)            -- AND b.SoDonHang <> a.SoDonHang  -- optional#(lf)          ),#(lf)          0)#(lf)        + COALESCE(#(lf)          (#(lf)            SELECT COUNT(*)#(lf)            FROM fact_sale_doanh_so_ban c#(lf)            WHERE#(lf)              LEFT(c.AutoCode, 2) = 'SP'#(lf)              AND c.DMC3 = a.NhomHang#(lf)              AND c.ContactPhone = a.DiDong#(lf)              AND c.CreateDate > a.NgayDat#(lf)              AND c.CreateDate <= DATE_ADD(a.NgayDat, INTERVAL 3 DAY)#(lf)              AND c.SOOrderAutoCode <> a.SoDonHang#(lf)          ),#(lf)          0)#(lf)    ELSE NULL#(lf)    END AS IsChased#(lf)FROM fact_ds_don_hang a", null, [EnableFolding=true]),
				    #"Uppercased Text" = Table.TransformColumns(Source,{{"NhomHang", Text.Upper, type text}})
				in
				    #"Uppercased Text"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

