table 'DIM_Danh mục_Phân khúc giá'
	lineageTag: 7ec57eb7-79f1-4d29-ab71-43b506e89814

	column 'Phân khúc giá'
		dataType: string
		lineageTag: 07126327-a533-4c96-804e-b421dc81684a
		summarizeBy: none
		sourceColumn: Phân khúc giá

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 409c8ffd-d32b-423c-ab52-cafd2b351866
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Phân khúc giá' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Lc3BEYAgDETRVpiccSYhGLEW4GgDjvZv2Hh8/7DbO3HaUnluyiQ0c6fiVrjA6q6wwtVtcIXN3eAdbm5hBEOQ9SAxeURZmxIjDWW8zHr96aQ5Pw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Phân khúc giá" = _t, Index = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Index", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

