table DIM_PromotionCode
	lineageTag: 13796efc-2cc5-4775-a98f-847dfde03523

	column PromotionCodeId
		dataType: int64
		formatString: 0
		lineageTag: 299dd3dc-4238-41a0-a231-60289105fb81
		summarizeBy: none
		sourceColumn: PromotionCodeId

		annotation SummarizationSetBy = Automatic

	column PromotionCode
		dataType: string
		lineageTag: 11fc6ab3-eb69-4df2-9f15-c521d08ef1db
		summarizeBy: none
		sourceColumn: PromotionCode

		annotation SummarizationSetBy = Automatic

	column BOD
		dataType: int64
		formatString: 0
		lineageTag: 2594f7b5-0d90-4909-aa5e-4a3e56a993d4
		summarizeBy: sum
		sourceColumn: BOD

		annotation SummarizationSetBy = Automatic

	column MKT
		dataType: int64
		formatString: 0
		lineageTag: 70363799-0ed2-42a8-9001-d82050cceceb
		summarizeBy: sum
		sourceColumn: MKT

		annotation SummarizationSetBy = Automatic

	column KD
		dataType: string
		lineageTag: 46dbdbed-5338-446e-a28c-ef35b870a09b
		summarizeBy: none
		sourceColumn: KD

		annotation SummarizationSetBy = Automatic

	column AM
		dataType: int64
		formatString: 0
		lineageTag: 23dfbb19-ca5b-4cd8-bab2-0b6038282756
		summarizeBy: sum
		sourceColumn: AM

		annotation SummarizationSetBy = Automatic

	column SM
		dataType: int64
		formatString: 0
		lineageTag: fc93d4ec-09c1-4db3-a441-7cbb76847dd0
		summarizeBy: sum
		sourceColumn: SM

		annotation SummarizationSetBy = Automatic

	column RSM
		dataType: int64
		formatString: 0
		lineageTag: 057e8d35-8e39-4c76-b5af-4f89a1f5254c
		summarizeBy: sum
		sourceColumn: RSM

		annotation SummarizationSetBy = Automatic

	column CHECK
		dataType: int64
		formatString: 0
		lineageTag: 67f21047-ff33-4a11-9aa8-cda32fb61f1f
		summarizeBy: sum
		sourceColumn: CHECK

		annotation SummarizationSetBy = Automatic

	column 'Chương trình' =
			
			[PromotionCodeId] & "-" & [PromotionCode]
		lineageTag: cdf7b815-f333-4a1e-ae4c-a916bd0433eb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DIM_PromotionCode = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vT1kIL6LsCWcGpYkKb3NHkvmLTMZCdSpABKDvsHYWl36uIEaZGB56SNCH5mFgz9va-OYfb8ur9k3h7E/pub?output=xlsx"), null, true),
				    Code_Sheet = Source{[Item="Code",Kind="Sheet"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Code_Sheet,{"Column3"}),
				    #"Removed Top Rows" = Table.Skip(#"Removed Columns",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Column1", Int64.Type}, {"Column2", type text}, {"BOD", Int64.Type}, {"MKT", Int64.Type}, {"KD", Int64.Type}, {"AM", Int64.Type}, {"SM", Int64.Type}, {"RSM", Int64.Type}, {"CHECK", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "PromotionCodeId"}, {"Column2", "PromotionCode"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([CHECK] <> 0)),
				    #"Appended Query" = Table.Combine({#"Filtered Rows", Code_BoSung}),
				    #"Filtered Rows1" = Table.SelectRows(#"Appended Query", each ([PromotionCodeId] <> null)),
				    #"Sorted Rows" = Table.Sort(#"Filtered Rows1",{{"PromotionCodeId", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

