table 'D_Danh mục_Miền'
	excludeFromModelRefresh
	lineageTag: 958eb045-e37f-4657-be91-45cae597d753

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 3b2b35c1-f29f-4a8b-aa9c-fef28179259f
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Miền
		dataType: string
		lineageTag: dbf31d07-20e6-4a91-bf6d-8134441a9e0a
		summarizeBy: none
		sourceColumn: Miền

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: c41b7602-0085-4bf7-ae04-2b1b3dfcacb8
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'D_Danh mục_Miền' = m
		mode: import
		queryGroup: 'Danh mục'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQrJP7wgT6Gw9OHuickgbqBSrE60khGQ6Zv5cHdjnoLTw13rQTIefmAZY4SMX2IuSNzZVyk2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Miền = _t, Region = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Miền", type text}, {"Region", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

