table Notes_Variable
	lineageTag: b637f0d2-1b6b-4161-acff-64544e718544

	column STT
		dataType: int64
		formatString: 0
		lineageTag: a8818445-b645-475f-8eb2-c5e185dcceb5
		summarizeBy: sum
		sourceColumn: STT

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Thông tin'
		dataType: string
		lineageTag: 8d385ba2-42b6-46db-94d5-ac3bf19ec8a1
		summarizeBy: none
		sourceColumn: Thông tin
		sortByColumn: STT

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Nội dung'
		dataType: string
		lineageTag: 9ec6ff27-c4c0-4693-b69e-d206cd8ca33a
		summarizeBy: none
		sourceColumn: Nội dung
		sortByColumn: STT

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Loại thông tin'
		dataType: string
		lineageTag: 4c3275ed-23de-4f83-b966-65b4945590ca
		summarizeBy: none
		sourceColumn: Loại thông tin

		annotation SummarizationSetBy = Automatic

	partition Notes_Variable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZHPSsNAEMZfZcipwkLx3wNIevBgezEUJPQQomRDm22RpjRHyUGkF/sAQqIHsVCoestSPEzIe+ybOLttLIiKp91vd+ab37fruta+xSyHK/kQQhB6glQnwCxh0CnTqOlwzEVgSq6GIPQNTDH3QXBVLAWMeKiKjxjKeajkTQw+jxMlUwGNlr1n9ZhrHVBzV8kZjK9xSXW09WCAazpu6x5Rm/d5DBMlX33wlVx6wDETwR/Gh78bO0reCQ5jbcEZdMtUk+KbCJr2zptBeV/lQg+dMThpU2SOj6RDXIhd5GplHmdAeUdfeRNcEJMqnn+KfmHXjEdkoxUtZ7iGyyFslfH29bRNzAlmMA23yrQeU9W5Kp40uSpeIv0xHN+jmt3h1YroAyAieRsz+FZsJvwf1xCUc/0eG6JG65Qy9D4B", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [STT = _t, #"Loại thông tin" = _t, #"Thông tin" = _t, #"Nội dung" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Thông tin", type text}, {"Nội dung", type text}, {"STT", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

