table 'DIM_Compare_Selected value'
	excludeFromModelRefresh
	lineageTag: 764b37b0-544b-402e-b009-03fb6f46727c

	column No
		dataType: int64
		formatString: 0
		lineageTag: 489decce-9d56-4420-9b2d-ff3ca74d1956
		summarizeBy: none
		sourceColumn: No

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: d4ddb69e-751b-4353-9ebc-3e253e341a4b
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Compare_Selected value' = m
		mode: import
		queryGroup: DIM\Metric
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfIrzU1KLVKK1YlWMgJyVdOVYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [No = _t, Value = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"No", Int64.Type}, {"Value", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

