table 'DIM_Phân quyền_User'
	isHidden
	lineageTag: f4aca0d0-c74c-4a13-bd0c-b60c6121c359

	column Path =
			
			PATH (
			    'DIM_Phân quyền_User'[Tên],
			    'DIM_Phân quyền_User'[Leader]
			)
		isHidden
		lineageTag: fb867046-17cf-4883-9c79-d08f296a06ea
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Tên
		dataType: string
		lineageTag: ab2e19fa-264f-4d78-803f-0af1f9d11b33
		summarizeBy: none
		sourceColumn: Tên

		annotation SummarizationSetBy = Automatic

	column Mail
		dataType: string
		lineageTag: 53bcfd65-91da-4fd1-af97-ce48a1fdb0b5
		summarizeBy: none
		sourceColumn: Mail

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 262bfbb9-85ee-43c3-992c-9e558d56a03f
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Workspace
		dataType: string
		lineageTag: f9d62fd4-1000-4ed4-95b4-b7de706ea851
		summarizeBy: none
		sourceColumn: Workspace

		annotation SummarizationSetBy = Automatic

	column 'Khu vực'
		dataType: string
		lineageTag: 26faeb04-e8f9-4240-b730-f1bf22661a30
		summarizeBy: none
		sourceColumn: Khu vực

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		lineageTag: 0927d73d-5a27-41b1-ae6c-d1275e4cdd8b
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	column Leader
		dataType: string
		lineageTag: a55fbfed-04ec-4645-bd2e-558375c4329c
		summarizeBy: none
		sourceColumn: Leader

		annotation SummarizationSetBy = Automatic

	column Startdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1467fe0d-d371-4cd1-9086-c71c40e4103d
		summarizeBy: none
		sourceColumn: Startdate

		variation Variation
			isDefault
			relationship: 145f0af1-3e3f-4be3-b82d-974713456ec0
			defaultHierarchy: LocalDateTable_4beeb383-0025-4346-b1fb-0a9666a47924.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'DIM_Phân quyền_User-91bc1c1e-91f7-427a-9556-a7e77b83a77c' = m
		mode: import
		queryGroup: 'Phân quyền'
		source =
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject="cellphones-data-platform"]){[Name="cellphones-data-platform"]}[Data], "---""dataset_id=42baee31-9dab-48af-b317-d89f4f8011db""#(lf)select *#(lf)from cellphones-data-platform.cps_DA_General_Transform.phan_quyen_bi_user", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"mail", "Mail"}, {"ten", "Tên"}, {"title", "Title"}, {"workspace", "Workspace"}, {"khu_vuc", "Khu vực"}, {"group", "Group"}, {"leader", "Leader"}, {"so_thang", "Startdate"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

