table 'DIM_Danh mục_Shop_SMKN'
	lineageTag: 4c0fb19a-4cea-4481-9f72-d0c7dbdeeb68

	column MIỀN
		dataType: string
		lineageTag: b4bd70bd-51c9-4cfa-a76c-d23808fd34a8
		summarizeBy: none
		sourceColumn: MIỀN

		annotation SummarizationSetBy = Automatic

	column SHOP
		dataType: string
		lineageTag: ab3d66e7-5432-4224-b472-a90fd548263e
		summarizeBy: none
		sourceColumn: SHOP

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 94c8fcc8-23ce-45ab-bc4f-6edf59c8c223
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: e7c1a835-2316-4210-a4d7-b6727e4641d9
			defaultHierarchy: LocalDateTable_e7378a41-e46d-426e-932a-7e12c99a05b1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SMKN
		dataType: string
		lineageTag: a546a1f6-e26c-4df5-92c7-d3039d70be31
		summarizeBy: none
		sourceColumn: SMKN

		annotation SummarizationSetBy = Automatic

	column AM =
			
			VAR am = RELATED('DIM_Danh mục_Phòng ban'[AM])
			RETURN IF('DIM_Danh mục_Shop_SMKN'[SMKN] = am,am,BLANK())
		lineageTag: 36ff0023-ff98-45d3-98e5-7c27e97eaa89
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Shop_SMKN' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vTwHaFyF_TWXVJLFL98imtp7wkwVkkQR_LnmBiN0h2P6uNXh7HTWHJ_tfEf12O55RbvAmth1hD1fbkS/pub?output=xlsx"), null, true),
				    #"Shop_SM KN_YM_Sheet" = Source{[Item="Shop_SM KN_YM",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Shop_SM KN_YM_Sheet", [PromoteAllScalars=true]),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"MIỀN", "SHOP"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "StartDate"}, {"Value", "SMKN"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"MIỀN", type text}, {"SHOP", type text}, {"StartDate", type date}, {"SMKN", type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Changed Type",{{"SMKN", Text.Upper, type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Uppercased Text", each [StartDate] >= #date(2024, 1, 1)),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","CPS-HNO-DDA-384XD","CPS-HNO-DDA-360XD",Replacer.ReplaceText,{"SHOP"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

