table 'DIM_Nguồn khảo sát'
	lineageTag: 9cef53d1-f726-4020-a605-63f345c3f174

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 2c7bef42-c8b3-415e-96dd-00008456431e
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Nguồn
		dataType: string
		lineageTag: 52ca9871-e2dd-442c-a00f-ddbb0000b1dd
		summarizeBy: none
		sourceColumn: Nguồn

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Nguồn khảo sát' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfLOeLhrcb5C8eGFJUqxOtFKRkAxx9KS/OTEnBywgDFQINg3WCk2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Index = _t, Nguồn = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Index", Int64.Type}, {"Nguồn", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

