table 'DIM_Danh mục_Miền'
	excludeFromModelRefresh
	lineageTag: ac703d81-c644-4f1c-92cc-4b0c626e7fcd

	column ID
		dataType: int64
		formatString: 0
		lineageTag: faa25659-7a70-4409-a4a4-8515437bb0a2
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Miền
		dataType: string
		lineageTag: b6962f05-b732-42bd-ad35-ba6ef0eda1c3
		summarizeBy: none
		sourceColumn: Miền

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Miền' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQrJP7wgT6Gw9OHuiclKsTrRSkZAQd/Mh7sb8xScHu5aDxE0Rgj6JeYqxcYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Miền = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Miền", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

