table 'DIM_Danh mục_Phòng ban'
	lineageTag: edecd406-29c9-41cd-8f5d-a582bbb83659

	column HaraID
		dataType: string
		lineageTag: 8612eb32-7635-4af0-95b0-e0f452606228
		summarizeBy: none
		sourceColumn: HaraID

		annotation SummarizationSetBy = Automatic

	column 'Mã Bộ phận'
		dataType: string
		lineageTag: 85265af7-070e-4cf5-9783-1e56b1092519
		summarizeBy: none
		sourceColumn: Mã Bộ phận

		annotation SummarizationSetBy = Automatic

	column 'Bộ phận'
		dataType: string
		lineageTag: e85f22e9-a2e9-48ff-943f-d3ed58789bd3
		summarizeBy: none
		sourceColumn: Bộ phận

		annotation SummarizationSetBy = Automatic

	column HaraWorkPlaceName
		dataType: string
		lineageTag: 197a9565-2795-4bcf-8ac8-c25260a1553f
		summarizeBy: none
		sourceColumn: HaraWorkPlaceName

		annotation SummarizationSetBy = Automatic

	column lv2
		dataType: string
		lineageTag: 3d5663f4-df48-4b43-9874-373ce5c60489
		summarizeBy: none
		sourceColumn: lv2

		annotation SummarizationSetBy = Automatic

	column lv3
		dataType: string
		lineageTag: 432aae71-aa1d-4d25-a43b-e62db0b8e24b
		summarizeBy: none
		sourceColumn: lv3

		annotation SummarizationSetBy = Automatic

	column lv4
		dataType: string
		lineageTag: 2c7b1621-5f1a-4a28-97b0-176d3b488821
		summarizeBy: none
		sourceColumn: lv4

		annotation SummarizationSetBy = Automatic

	column lv5
		dataType: string
		lineageTag: 2a4e65c6-fe64-4c9a-9447-def0e3c5b169
		summarizeBy: none
		sourceColumn: lv5

		annotation SummarizationSetBy = Automatic

	column lv6
		dataType: string
		lineageTag: bf080c82-8699-4145-852c-bcf35102b0eb
		summarizeBy: none
		sourceColumn: lv6

		annotation SummarizationSetBy = Automatic

	column lv7
		dataType: string
		lineageTag: 32d57f54-ce97-4b52-af87-ef9d088e770f
		summarizeBy: none
		sourceColumn: lv7

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: de43a072-40f6-46e4-9fd7-b00a3a2561f9
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 621a5f13-d16c-40df-a455-8c5bce40c4f9
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BranchId
		dataType: int64
		formatString: 0
		lineageTag: 535eb4d9-7f5d-442f-aad6-e6242c5d7426
		summarizeBy: count
		sourceColumn: BranchId

		annotation SummarizationSetBy = Automatic

	column IsInactive
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 96a16e02-ae0b-4a67-9656-cd3f0697156b
		summarizeBy: none
		sourceColumn: IsInactive

		annotation SummarizationSetBy = Automatic

	column 'Công ty'
		dataType: string
		lineageTag: ffacad42-8832-4617-a5a1-06e44c6ead0f
		summarizeBy: none
		sourceColumn: Công ty

		annotation SummarizationSetBy = Automatic

	column Khối
		dataType: string
		lineageTag: 98b56eef-88cf-4c3d-807a-936f9640bffb
		summarizeBy: none
		sourceColumn: Khối

		annotation SummarizationSetBy = Automatic

	column Phòng
		dataType: string
		lineageTag: 0675670c-0e29-4af7-8707-50d0c697b389
		summarizeBy: none
		sourceColumn: Phòng

		annotation SummarizationSetBy = Automatic

	column Miền
		dataType: string
		lineageTag: 4771ad10-b159-4765-84a5-769d1bc4fa4d
		summarizeBy: none
		sourceColumn: Miền

		annotation SummarizationSetBy = Automatic

	column Vùng
		dataType: string
		lineageTag: 75612768-e3fb-4cbe-9691-6e29aab06e3f
		summarizeBy: none
		sourceColumn: Vùng

		annotation SummarizationSetBy = Automatic

	column 'Tên ngắn gọn'
		dataType: string
		lineageTag: ae8c04d7-e421-4fea-a3f3-2e186763172f
		summarizeBy: none
		sourceColumn: Tên ngắn gọn

		annotation SummarizationSetBy = Automatic

	column 'Ngày bán cuối cùng'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 54947db7-85a0-49f9-89b8-5b7098e08d01
		summarizeBy: none
		sourceColumn: Ngày bán cuối cùng

		variation Variation
			isDefault
			relationship: b2147f82-dcc5-4ad9-83c0-133bcfb10d0e
			defaultHierarchy: LocalDateTable_716fcdb8-9391-4eca-8d0c-26b41f1ae8ff.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ngày khai trương'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d28ec84e-1fc8-4609-968f-31c5cf63e31e
		summarizeBy: none
		sourceColumn: Ngày khai trương

		variation Variation
			isDefault
			relationship: 4b62103a-dc03-4089-9d3f-d9963e9077ac
			defaultHierarchy: LocalDateTable_58a0d8ff-dd1f-4be3-8ace-abf5559d0668.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Diện tích tổng'
		dataType: double
		lineageTag: 1a1debed-4757-49a7-8cb4-020a0b6720f7
		summarizeBy: sum
		sourceColumn: Diện tích tổng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CostCenter
		dataType: string
		lineageTag: a84cabaa-10e7-4847-ac09-2d52580f65e8
		summarizeBy: none
		sourceColumn: CostCenter

		annotation SummarizationSetBy = Automatic

	column AM
		dataType: string
		lineageTag: 66ee3fc0-98bd-4523-a415-4c92f7a8e3e2
		summarizeBy: none
		sourceColumn: AM

		annotation SummarizationSetBy = Automatic

	column RSM
		dataType: string
		lineageTag: 38c0ab21-8798-4011-8be7-81692839e025
		summarizeBy: none
		sourceColumn: RSM

		annotation SummarizationSetBy = Automatic

	column 'Mã kho'
		dataType: string
		lineageTag: 1865b4f2-2f2a-4ec7-a676-b0286d71be08
		summarizeBy: none
		sourceColumn: Mã kho

		annotation SummarizationSetBy = Automatic

	column 'Địa chỉ'
		dataType: string
		lineageTag: 3e6185eb-db3b-4b6f-82b2-def1f4aae7f1
		summarizeBy: none
		sourceColumn: Địa chỉ

		annotation SummarizationSetBy = Automatic

	column apple_location_id
		dataType: string
		lineageTag: 62341b9a-7a9d-478c-8f7f-905336157e85
		summarizeBy: none
		sourceColumn: apple_location_id

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 710ecb6d-471a-4d44-a4fc-1cfc8bbff069
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Province
		dataType: string
		lineageTag: a9c3f0ba-4bb3-4951-80a3-500fed02f48a
		summarizeBy: none
		sourceColumn: Province

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: 45a3a300-e30d-458a-951f-1483adaa3ec6
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column 'Chiều ngang'
		dataType: double
		lineageTag: dcd87451-e31a-41c3-84c6-0ae2e00f62a3
		summarizeBy: sum
		sourceColumn: Chiều ngang

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Chiều rộng'
		dataType: double
		lineageTag: 5f510129-c420-4d4e-a92b-98981135ca80
		summarizeBy: sum
		sourceColumn: Chiều rộng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Diện tích bán hàng'
		dataType: double
		lineageTag: 34fe0c0b-ea26-4bc7-ba1a-c154b7e5e896
		summarizeBy: sum
		sourceColumn: Diện tích bán hàng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsActive
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 79795993-c7ef-41e6-9c94-8c0f21bb24fa
		summarizeBy: none
		sourceColumn: IsActive

		annotation SummarizationSetBy = Automatic

	column SIZE
		dataType: string
		lineageTag: e008a4d4-47b0-42a6-ac4d-09591fd74f3d
		summarizeBy: none
		sourceColumn: SIZE

		annotation SummarizationSetBy = Automatic

	column SM/SUM = [SM/SUP]
		lineageTag: a4e174b3-5e33-4954-8b58-f0f7e3dfce78
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Cửa hàng gộp'
		dataType: string
		lineageTag: 6d659274-5527-46d1-8df2-accc8c33ded5
		summarizeBy: none
		sourceColumn: Cửa hàng gộp

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Danh mục_Phòng ban' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([Implementation="2.0"]){[Name="cellphones-data-platform"]}[Data], "---""dataset_id=846a68ee-cfb9-40fd-940b-7f8fd45fb141""#(lf)select #(lf)hara_id#(tab)HaraID,#(lf)hara_workplace_name HaraWorkPlaceName,#(lf)ma_bo_phan#(tab)`Mã Bộ phận`,#(lf)bo_phan#(tab)`Bộ phận`,#(lf)ma_kho#(tab)`Mã kho`,#(lf)level_2#(tab)lv2,#(lf)level_3#(tab)lv3,#(lf)level_4#(tab)lv4,#(lf)level_5#(tab)lv5,#(lf)level_6#(tab)lv6,#(lf)level_7#(tab)lv7,#(lf)short_name#(tab)`Tên ngắn gọn`,#(lf)dia_chi_shop#(tab)`Địa chỉ`,#(lf)Latitude#(tab),#(lf)Longitude#(tab),#(lf)branch_id#(tab)BranchId,#(lf)apple_location_id,#(tab)#(lf)oracle_code#(tab)CostCenter,#(lf)van_phong_cua_hang Type,#(lf)cong_ty#(tab)`Công ty`,#(lf)mien `Miền`,#(lf)tinh_thanh_pho#(tab)Province,#(lf)quan_huyen#(tab)District,#(lf)vung#(tab)`Vùng`,#(lf)khoi#(tab)`Khối`,#(lf)phong#(tab)`Phòng`,#(lf)khai_truong#(tab)`Ngày khai trương`,#(lf)dong_cua#(tab)`Ngày bán cuối cùng`,#(lf)ngang_m#(tab)`Chiều ngang`,#(lf)sau_m#(tab)`Chiều rộng`,#(lf)tong_m2#(tab)`Diện tích tổng`,#(lf)dien_tich_ban_hang#(tab)`Diện tích bán hàng`,#(lf)size#(tab)SIZE,#(lf)kn_am#(tab)AM,#(lf)rsm#(tab)RSM,#(lf)is_active#(tab)IsActive,#(lf)is_inactive#(tab)IsInactive,#(lf)cua_hang_gop    `Cửa hàng gộp`#(lf)from#(lf)  `cellphones-data-platform.cps_DA_General_Transform.dim_department`#(lf)where cong_ty = 'CPS'", null, [EnableFolding=true]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([HaraID] <> null)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"HaraID", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

