table 'DIM_Store_Measure selection'
	lineageTag: a82e985d-76cf-4bcc-b6b6-66bd4202a27f

	column Measure
		dataType: string
		lineageTag: c4a3a514-be6c-4259-ba59-8a36a1c2476a
		summarizeBy: none
		sourceColumn: Measure

		annotation SummarizationSetBy = Automatic

	column 'Measure type'
		dataType: string
		lineageTag: 6082d580-011e-4c2e-b501-eeabe5c9cf6a
		summarizeBy: none
		sourceColumn: Measure type

		annotation SummarizationSetBy = Automatic

	column No
		dataType: int64
		formatString: 0
		lineageTag: 82f551c2-ba43-4ef9-84a0-4fe27a0807f3
		summarizeBy: none
		sourceColumn: No

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Store_Measure selection-67e9d25e-9446-48d4-a3ad-6c30426ed48d' = m
		mode: import
		queryGroup: DIM\Metric
		source =
				let
				    Source = Excel.Workbook(Web.Contents(GGsheet_Palexy), null, true),
				    Dim_Store_Measure_Sheet = Source{[Item="Dim_Store_Measure",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Dim_Store_Measure_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"No", Int64.Type}, {"Measure", type text}, {"Measure type", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

