table D_User
	lineageTag: a95fe148-6f4e-496d-acb8-5b4272123f75

	column Tên
		dataType: string
		lineageTag: f25b479b-4c0e-4efe-854c-df3024e36c5e
		summarizeBy: none
		sourceColumn: Tên

		annotation SummarizationSetBy = Automatic

	column Mail
		dataType: string
		lineageTag: 5283b1d9-a85b-4522-936d-9466cf178315
		summarizeBy: none
		sourceColumn: Mail

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 35361f6c-0046-4b27-8476-985e3b9fbd65
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Workspace
		dataType: string
		lineageTag: 78429d95-02c5-4a78-ac2f-9b79a03c103e
		summarizeBy: none
		sourceColumn: Workspace

		annotation SummarizationSetBy = Automatic

	column 'Khu vực'
		dataType: string
		lineageTag: f8d3b7d0-3822-46c1-8d95-ac8050919da6
		summarizeBy: none
		sourceColumn: Khu vực

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		lineageTag: bfe79be7-d424-4ad3-802e-3cf9b78b5c29
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	column Leader
		dataType: string
		lineageTag: cbef359b-3119-4de5-ab25-c67cf981e9ed
		summarizeBy: none
		sourceColumn: Leader

		annotation SummarizationSetBy = Automatic

	column Startdate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 96faa208-c5f0-4254-ab6e-70906b57fbe7
		summarizeBy: none
		sourceColumn: Startdate

		variation Variation
			isDefault
			relationship: 505078cc-f1d1-405b-81ed-fab94f6de6f2
			defaultHierarchy: LocalDateTable_d14f45a1-3bd5-4af6-8197-78228ec83513.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Path =
			
			PATH( 'D_User'[Tên], 'D_User'[Leader] )
		lineageTag: c0ed5cf2-1212-47df-98d1-3146957243aa
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition D_User = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject="cellphones-data-platform"]){[Name="cellphones-data-platform"]}[Data], "--“dataset_id=0c443b5c-c2db-4617-b273-e61ac25f9b66”#(lf)select *#(lf)from cellphones-data-platform.cps_DA_General_Transform.phan_quyen_bi_user", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"mail", "Mail"}, {"ten", "Tên"}, {"title", "Title"}, {"workspace", "Workspace"}, {"khu_vuc", "Khu vực"}, {"group", "Group"}, {"leader", "Leader"}, {"so_thang", "Startdate"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each not Text.Contains([Mail], "s01202.hien@cellphones.com.vn") and not Text.Contains([Mail], "thuy.nt@cellphones.com.vn")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each not Text.Contains([Tên], "CPS-HNO-SHOPONLINE") and not Text.Contains([Tên], "CPS-HNO-DDA-B2B")),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each not Text.Contains([Tên], "Vùng Hà Nội OPS") and not Text.Contains([Tên], "CPS-HNO-DDA-ON98TH")),
				    #"Appended Query" = Table.Combine({#"Filtered Rows2", D_User_Updated})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

