table D_SelectedMeasure_Late
	excludeFromModelRefresh
	lineageTag: 1af0b82b-88e0-49cc-aeab-b9108b46043c

	column No
		dataType: int64
		formatString: 0
		lineageTag: abf37c33-d6ba-4218-b038-87e1628f3f73
		summarizeBy: sum
		sourceColumn: No

		annotation SummarizationSetBy = Automatic

	column Measure
		dataType: string
		lineageTag: 6120a8f5-87c9-48f9-994c-07692da2b3c7
		summarizeBy: none
		sourceColumn: Measure
		sortByColumn: No

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition D_SelectedMeasure_Late = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQrOyC9QitWJVjICczILClKLwHxjqKRCTKmBgZGZArKcCVDOxQPMNAUyg0KUYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [No = _t, Measure = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"No", Int64.Type}, {"Measure", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

