DEFINE
    VAR __Base =
        SELECTCOLUMNS(
            FILTER(
                'FACT_Sale_Doanh số bán',
                NOT ISBLANK('FACT_Sale_Doanh số bán'[phone])
                    && TRIM('FACT_Sale_Doanh số bán'[phone] & "") <> ""
            ),
            "date", 'FACT_Sale_Doanh số bán'[date],
            "phone", TRIM('FACT_Sale_Doanh số bán'[phone] & ""),
            "autocode", 'FACT_Sale_Doanh số bán'[autocode],
            "user_pseudo_id", TRIM('FACT_Sale_Doanh số bán'[user_pseudo_id] & ""),
            "device_category", TRIM('FACT_Sale_Doanh số bán'[device_category] & ""),
            "mobile_brand_name", TRIM('FACT_Sale_Doanh số bán'[mobile_brand_name] & ""),
            "mobile_model_name", TRIM('FACT_Sale_Doanh số bán'[mobile_model_name] & "")
        )

EVALUATE
FILTER(
    __Base,
    [user_pseudo_id] <> ""
        && [device_category] <> ""
        && [mobile_brand_name] <> ""
        && [mobile_model_name] <> ""
)
ORDER BY [date] DESC, [phone], [autocode]
